# -*- coding: utf-8 -*-
"""PEPTIDEX — base de datos técnica.  Parte B: BEAUTY y LONGEVITY."""

BEAUTY = [

{ "id":"CU", "name":"GHK-Cu", "aka":"Cobre tripéptido-1, glicil-L-histidil-L-lisina cobre(II)",
  "cls":"Complejo tripéptido-cobre",
  "cas":"89030-95-5 (complejo de cobre); 49557-75-7 (GHK libre)",
  "formula":"C14H22CuN6O4", "mw":401.93, "len":3,
  "seq":"Gly-His-Lys, acomplejado con Cu(II) en relación 1:1",
  "purpose":"El compuesto ancla de la línea BEAUTY. Investigación de remodelado dérmico, síntesis de colágeno y cicatrización.",
  "contains":"Complejo azul intenso de tripéptido y cobre(II), liofilizado. El color azul es el propio complejo: un polvo blanco etiquetado GHK-Cu es GHK libre sin cobre, y ése es el modo de fallo más frecuente y más fácil de detectar del catálogo — se ve a simple vista.",
  "mechanism":"GHK es un fragmento de la cadena alfa-2 del colágeno tipo I, liberado al degradarse la matriz: funciona como señal endógena de «hay daño aquí». Su afinidad por el cobre(II) es tal que lo captura de la albúmina. El complejo estimula síntesis de colágeno, elastina, proteoglicanos y glicosaminoglicanos, modula MMP y TIMP, y el cobre entregado es cofactor de la lisil-oxidasa que entrecruza el colágeno nuevo.",
  "research":[
    "Aumento de densidad de colágeno y mejora de firmeza y arrugas en ensayos clínicos dermatológicos (humano, tópico).",
    "Aceleración de cicatrización en úlcera diabética y en herida quirúrgica (humano, tópico).",
    "Estimulación de folículo piloso y aumento de tamaño de folículo (humano, tópico).",
    "Análisis de expresión génica: GHK-Cu modula más de 4000 genes humanos hacia un perfil más juvenil (Pickart et al.).",
    "Los niveles plasmáticos de GHK descienden de ~200 ng/mL a los 20 años a ~80 ng/mL a los 60.",
    "La evidencia sólida es TÓPICA. La vía inyectable no tiene ensayos clínicos equivalentes."],
  "halflife":"Corta en plasma. El interés terapéutico es local.",
  "recon":"Agua bacteriostática. Muy soluble; la solución debe quedar azul clara. Turbidez o precipitado verde indica disociación del cobre.",
  "storage":"Liofilizado: −20 °C protegido de la luz. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"El complejo se disocia a pH ácido y en presencia de quelantes (EDTA, citrato). No mezclar con vitamina C ni con ácidos: el cobre libre resultante es prooxidante y el tripéptido pierde toda su función.",
  "handling":"Complejo de cobre. Evitar contacto prolongado con piel; el cobre libre es irritante.",
  "flags":["Aprobado como ingrediente cosmético; NO aprobado para uso inyectable.",
           "Verificar color azul del liofilizado: es la comprobación de identidad más barata que existe.",
           "Incompatible con quelantes y con ácido ascórbico."] },

{ "id":"AC", "name":"AHK-Cu", "aka":"Cobre tripéptido-3, alanil-L-histidil-L-lisina cobre(II)",
  "cls":"Complejo tripéptido-cobre",
  "cas":"148579-77-1 (complejo)", "formula":"C15H24CuN6O4", "mw":415.94, "len":3,
  "seq":"Ala-His-Lys, acomplejado con Cu(II)",
  "purpose":"Investigación de folículo piloso y angiogénesis dérmica. Es el análogo de GHK-Cu con la glicina sustituida por alanina.",
  "contains":"Complejo azul de tripéptido y cobre(II), liofilizado. Mismo criterio visual que GHK-Cu: si no es azul, no es el complejo.",
  "mechanism":"Análogo estructural de GHK-Cu con perfil desplazado hacia estimulación de VEGF y de proliferación de papila dérmica. La sustitución Gly→Ala añade un metilo que cambia la afinidad relativa por distintos objetivos.",
  "research":[
    "Aumento de proliferación de células de papila dérmica y de VEGF in vitro.",
    "Aumento de longitud de tallo piloso en folículo humano cultivado ex vivo.",
    "Uso cosmético establecido en formulaciones capilares.",
    "Base de evidencia sustancialmente menor que la de GHK-Cu; casi toda in vitro."],
  "halflife":"Corta.",
  "recon":"Agua bacteriostática. Solución azul clara.",
  "storage":"Liofilizado: −20 °C protegido de la luz. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Mismas incompatibilidades que GHK-Cu: quelantes, pH ácido, ascorbato.",
  "handling":"Complejo de cobre. Evitar contacto prolongado con piel.",
  "flags":["Aprobado como ingrediente cosmético; NO aprobado para uso inyectable.",
           "Evidencia mayormente in vitro."] },

{ "id":"MX", "name":"Matrixyl", "aka":"Palmitoil pentapéptido-4, Pal-KTTKS, Matrixyl (Sederma)",
  "cls":"Matriquina lipidada",
  "cas":"214047-00-4", "formula":"C39H75N9O9", "mw":802.1, "len":5,
  "seq":"Palmitoil-Lys-Thr-Thr-Lys-Ser",
  "purpose":"Investigación de estimulación de matriz extracelular. Es un ingrediente cosmético con historia comercial de veinticinco años, no un compuesto experimental.",
  "contains":"Pentapéptido con cadena palmítica de 16 carbonos, liofilizado. La cadena grasa es lo que le permite atravesar el estrato córneo — sin ella, KTTKS no penetra.",
  "mechanism":"KTTKS es un subfragmento del propéptido C-terminal del colágeno tipo I. Al igual que GHK, es una señal de recambio de matriz: su presencia indica al fibroblasto que hay colágeno degradándose y dispara síntesis de colágeno I, III y de fibronectina.",
  "research":[
    "Reducción de rugosidad cutánea y de profundidad de arrugas frente a vehículo en ensayo doble ciego de 12 semanas (humano, tópico).",
    "Estimulación de colágeno I, III y fibronectina en fibroblasto humano in vitro.",
    "Lanzado por Sederma en el año 2000; uno de los péptidos cosméticos más estudiados y con más historial de uso.",
    "Toda la evidencia es tópica. No hay datos de administración sistémica."],
  "halflife":"No aplica en uso tópico.",
  "recon":"Poco soluble en agua por la cadena palmítica. Requiere codisolvente (propilenglicol, etanol) o formulación en emulsión.",
  "storage":"Liofilizado: −20 °C. En formulación: según el vehículo.",
  "stability":"Buena. Las dos treoninas y la serina pueden hidrolizar en medio muy alcalino.",
  "handling":"Ingrediente cosmético de bajo riesgo.",
  "flags":["Ingrediente cosmético. NO existe evidencia ni indicación para uso inyectable.",
           "La solubilidad acuosa limitada es un dato de formulación, no un defecto del lote."] },

{ "id":"GL", "name":"GLOW Blend", "aka":"Glow 70, GHK-Cu + BPC-157 + TB-500",
  "cls":"Mezcla liofilizada de tres péptidos",
  "cas":None, "formula":None, "mw":None, "len":None,
  "seq":"GHK-Cu  +  GEPPPGKPADDAGLV  +  Ac-LKKTETQ-OH",
  "purpose":"Formulación combinada de estética y reparación. La presentación de 70 MG corresponde a la proporción de mercado habitual: 50 mg de GHK-Cu, 10 mg de BPC-157 y 10 mg de TB-500.",
  "contains":"Tres péptidos coliofilizados. La proporción declarada debe leerse en la etiqueta del lote — 50/10/10 es lo convencional pero no es un estándar. El polvo debe presentar el azul del complejo de cobre; su ausencia indica que el GHK no lleva cobre.",
  "mechanism":"Ver las tres fichas individuales. No hay literatura sobre la mezcla; la combinación es de formulación, no de hallazgo.",
  "research":["No existe literatura sobre la mezcla. Toda la evidencia corresponde a cada componente por separado, y en el caso de GHK-Cu es evidencia tópica."],
  "halflife":"Ver fichas individuales.",
  "recon":"Agua bacteriostática. Los tres son solubles. La solución debe quedar azul.",
  "storage":"Liofilizado: −20 °C protegido de la luz. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Limitada por el complejo de cobre, que es el componente más frágil químicamente.",
  "handling":"Contiene cobre. Evitar quelantes y ácido ascórbico.",
  "flags":["Sin aprobación regulatoria.","Dos de los tres componentes están prohibidos por la AMA/WADA.",
           "El CoA debe reportar pureza y proporción de CADA componente."] },

{ "id":"KL", "name":"KLOW Blend", "aka":"Klow 80, KPV + GHK-Cu + BPC-157 + TB-500",
  "cls":"Mezcla liofilizada de cuatro péptidos",
  "cas":None, "formula":None, "mw":None, "len":None,
  "seq":"KPV  +  GHK-Cu  +  GEPPPGKPADDAGLV  +  Ac-LKKTETQ-OH",
  "purpose":"GLOW con el componente antiinflamatorio añadido. La presentación de 80 MG corresponde a 50 mg de GHK-Cu más 10 mg de cada uno de los otros tres.",
  "contains":"Cuatro péptidos coliofilizados. Proporción declarada por lote. Mismo criterio de color azul que GLOW.",
  "mechanism":"Ver las cuatro fichas individuales. KPV aporta la vía antiinflamatoria melanocortínica, que es mecanísticamente independiente de las otras tres.",
  "research":["No existe literatura sobre la mezcla. Toda la evidencia corresponde a los componentes por separado."],
  "halflife":"Ver fichas individuales.",
  "recon":"Agua bacteriostática. Solución azul.",
  "storage":"Liofilizado: −20 °C protegido de la luz. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Limitada por el complejo de cobre.",
  "handling":"Contiene cobre. Evitar quelantes y ácido ascórbico.",
  "flags":["Sin aprobación regulatoria.","Componentes prohibidos por la AMA/WADA.",
           "El CoA debe reportar pureza y proporción de CADA uno de los cuatro componentes.",
           "Una mezcla de cuatro péptidos es analíticamente exigente: exigir HPLC con resolución de los cuatro picos."] },

{ "id":"MT1", "name":"Melanotan I", "aka":"Afamelanotida, Scenesse, NDP-α-MSH, Melanotan-1",
  "cls":"Análogo lineal de α-MSH",
  "cas":"75921-69-6", "formula":"C78H111N21O19", "mw":1646.85, "len":13,
  "seq":"Ac-Ser-Tyr-Ser-Nle-Glu-His-D-Phe-Arg-Trp-Gly-Lys-Pro-Val-NH2",
  "purpose":"Investigación de fotoprotección por melanogénesis. Es el único de los dos melanotanos que llegó a aprobación.",
  "contains":"Tridecapéptido sintético con norleucina en posición 4 y D-fenilalanina en 7, liofilizado, sal de acetato.",
  "mechanism":"Agonista del receptor de melanocortina 1 (MC1R) en el melanocito, con selectividad razonable. Estimula la síntesis de eumelanina, el pigmento fotoprotector. Las dos sustituciones respecto al α-MSH nativo lo hacen ~1000 veces más potente y mucho más resistente a proteasas.",
  "research":[
    "Aprobado por la EMA (2014) y la FDA (2019) como Scenesse, implante subcutáneo, para prevención de fototoxicidad en protoporfiria eritropoyética.",
    "Aumento de densidad de melanina y de tolerancia a exposición lumínica (humano, fase 3).",
    "Perfil de seguridad razonablemente caracterizado en la población de la indicación.",
    "El producto aprobado es un implante de liberación lenta, no una inyección diaria."],
  "halflife":"~1 h como péptido libre; el implante aprobado libera durante ~2 meses.",
  "recon":"Agua bacteriostática. Soluble.",
  "storage":"Liofilizado: −20 °C protegido de la luz. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Contiene Trp (fotosensible) y His. La norleucina sustituye a la metionina precisamente para eliminar el sitio oxidable — es un diseño más estable que el α-MSH nativo.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Existe versión aprobada (Scenesse, implante); el material de investigación NO es ese producto.",
           "La melanogénesis inducida no sustituye a la vigilancia dermatológica: oscurecer nevos preexistentes puede enmascarar cambios."] },

{ "id":"MT2", "name":"Melanotan II", "aka":"MT-II, PT-141 precursor, Melanotan-2",
  "cls":"Análogo cíclico de α-MSH, no selectivo",
  "cas":"121062-08-6", "formula":"C50H69N15O9", "mw":1024.18, "len":7,
  "seq":"Ac-Nle-cyclo[Asp-His-D-Phe-Arg-Trp-Lys]-NH2 (ciclado por lactama Asp-Lys)",
  "purpose":"Investigación de melanogénesis. Es el compuesto del que se derivó PT-141, y comparte con él la falta de selectividad de receptor.",
  "contains":"Heptapéptido cíclico sintético, liofilizado, sal de acetato. La ciclación por puente lactama es lo que le da la rigidez conformacional y la potencia.",
  "mechanism":"Agonista NO selectivo de melanocortinas: activa MC1R (pigmento), MC3R y MC4R (apetito, función sexual, autonómico). Esa promiscuidad explica que produzca a la vez bronceado, erección espontánea, náusea y supresión de apetito — no son efectos secundarios independientes, son el mismo mecanismo actuando donde no se quería.",
  "research":[
    "Melanogénesis dependiente de dosis (humano, estudios pequeños).",
    "Erección espontánea documentada de forma consistente — el hallazgo que llevó al desarrollo de PT-141.",
    "Náusea y rubor frecuentes y dependientes de dosis.",
    "Informes de caso publicados de melanoma y de cambios en nevos displásicos en usuarios; la causalidad no está establecida pero la señal existe.",
    "Nunca completó desarrollo clínico. Sin aprobación en ninguna jurisdicción."],
  "halflife":"~1–2 h.",
  "recon":"Agua bacteriostática. Soluble.",
  "storage":"Liofilizado: −20 °C protegido de la luz. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Buena: la ciclación lo protege de exopeptidasas. El Trp es fotosensible.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria en ninguna jurisdicción.",
           "Agonista no selectivo: los efectos sobre apetito, presión arterial y función sexual son intrínsecos al mecanismo.",
           "Informes de caso de melanoma en usuarios. Advertencias sanitarias emitidas por agencias del Reino Unido, Australia y países nórdicos."] },

{ "id":"PT", "name":"PT-141", "aka":"Bremelanotida, Vyleesi",
  "cls":"Agonista de melanocortina MC3R/MC4R",
  "cas":"189691-06-3", "formula":"C50H68N14O10", "mw":1025.16, "len":7,
  "seq":"Ac-Nle-cyclo[Asp-His-D-Phe-Arg-Trp-Lys]-OH (metabolito desamidado de Melanotan II)",
  "purpose":"Investigación de función sexual por vía central. Es el metabolito activo de Melanotan II, desarrollado hasta aprobación.",
  "contains":"Heptapéptido cíclico sintético, liofilizado, sal de acetato. Difiere de MT-II sólo en el extremo C: ácido libre en lugar de amida, lo que reduce la actividad sobre MC1R y por tanto el bronceado.",
  "mechanism":"Agonista de MC3R y MC4R en el sistema nervioso central. Actúa sobre las vías del deseo en hipotálamo, no sobre la vasculatura periférica — es un mecanismo completamente distinto al de los inhibidores de PDE5, y por eso funciona en casos donde aquéllos no.",
  "research":[
    "Aprobado por la FDA en 2019 como Vyleesi para trastorno del deseo sexual hipoactivo en mujeres premenopáusicas.",
    "Ensayos fase 3 RECONNECT: mejora estadísticamente significativa pero de magnitud modesta (humano, n>1200).",
    "Náusea en ~40 % de las participantes, el efecto adverso limitante.",
    "Aumento transitorio de presión arterial y descenso de frecuencia cardiaca tras la dosis: contraindicado en hipertensión no controlada y en enfermedad cardiovascular.",
    "Hiperpigmentación focal con uso repetido, por actividad residual sobre MC1R."],
  "halflife":"~2.7 h.",
  "recon":"Agua bacteriostática. Soluble.",
  "storage":"Liofilizado: −20 °C protegido de la luz. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Buena. Trp fotosensible.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Existe versión aprobada por FDA (Vyleesi); el material de investigación NO es ese producto.",
           "Contraindicado en hipertensión no controlada y enfermedad cardiovascular (etiqueta del innovador).",
           "Náusea muy frecuente y dependiente de dosis."] },

{ "id":"NP8", "name":"Snap-8", "aka":"Acetil octapéptido-3, acetil octapéptido-1",
  "cls":"Péptido cosmético mimético de SNAP-25",
  "cas":"868844-74-0", "formula":"C34H60N14O14", "mw":889.0, "len":8,
  "seq":"Ac-Glu-Glu-Met-Gln-Arg-Arg-Ala-Asp-NH2",
  "purpose":"Investigación de arruga de expresión por inhibición competitiva de la liberación de neurotransmisor. Es un ingrediente cosmético tópico.",
  "contains":"Octapéptido sintético acetilado y amidado, liofilizado.",
  "mechanism":"Reproduce el extremo N-terminal de SNAP-25, una de las tres proteínas del complejo SNARE que fusiona la vesícula de acetilcolina con la membrana presináptica. Al competir por su posición en el complejo, reduce la eficiencia de la exocitosis y con ella la contracción muscular. Es el mismo blanco que la toxina botulínica pero por un mecanismo competitivo y reversible, no proteolítico — y con una potencia que no admite comparación.",
  "research":[
    "Reducción de profundidad de arruga de ~25–35 % frente a basal en estudios del fabricante (humano, tópico, 28 días).",
    "La evidencia independiente revisada por pares es escasa; la mayor parte procede del propio proveedor de la materia prima.",
    "Toda la evidencia es tópica. No hay datos de administración inyectable ni justificación mecanística para ella."],
  "halflife":"No aplica en uso tópico.",
  "recon":"Soluble en agua y en glicoles. Formulación al 3–10 % es lo habitual en cosmética.",
  "storage":"Liofilizado: −20 °C. En formulación: según vehículo.",
  "stability":"Contiene metionina: oxidable. Es la vulnerabilidad principal de la molécula y conviene formularla con antioxidante.",
  "handling":"Ingrediente cosmético de bajo riesgo.",
  "flags":["Ingrediente cosmético TÓPICO. No existe evidencia ni indicación para uso inyectable.",
           "Evidencia mayoritariamente del fabricante."] },

{ "id":"GT", "name":"Glutathione", "aka":"GSH, L-glutatión reducido, γ-Glu-Cys-Gly",
  "cls":"Tripéptido tiol endógeno",
  "cas":"70-18-8", "formula":"C10H17N3O6S", "mw":307.32, "len":3,
  "seq":"γ-Glu-Cys-Gly (el enlace glutámico es gamma, no alfa: por eso las peptidasas normales no lo cortan)",
  "purpose":"El antioxidante intracelular principal del organismo. Investigación de estrés oxidativo, detoxificación hepática y despigmentación.",
  "contains":"Tripéptido en forma reducida (GSH), liofilizado. La distinción entre forma reducida y oxidada (GSSG) es la especificación crítica: sólo la reducida tiene el tiol libre que hace el trabajo. Un CoA que no reporte la relación GSH/GSSG es insuficiente.",
  "mechanism":"El tiol de la cisteína es el grupo funcional: dona electrones para neutralizar peróxidos vía glutatión peroxidasa, y conjuga xenobióticos vía glutatión S-transferasa en la fase II hepática. En melanocito inhibe la tirosinasa y desplaza la síntesis de eumelanina a feomelanina, que es el fundamento del uso despigmentante.",
  "research":[
    "Aclaramiento cutáneo medible con administración oral y tópica en ensayos pequeños (humano, población asiática).",
    "La biodisponibilidad oral del glutatión intacto es baja; buena parte se hidroliza a sus aminoácidos.",
    "El uso intravenoso para aclaramiento cutáneo carece de ensayos de seguridad adecuados. La FDA de Filipinas emitió una advertencia formal en 2011 tras casos de reacciones graves, incluidos síndrome de Stevens-Johnson y disfunción tiroidea y renal.",
    "Uso establecido como adyuvante en intoxicación por paracetamol (como precursor, N-acetilcisteína) y en quimioterapia con cisplatino."],
  "halflife":"Muy corta en plasma (minutos). El pool relevante es intracelular.",
  "recon":"Agua bacteriostática o agua estéril. Muy soluble. La solución debe ser incolora; amarilleamiento indica oxidación.",
  "storage":"Liofilizado: −20 °C, envase sellado bajo atmósfera inerte si es posible. Reconstituido: 2–8 °C, uso a corto plazo (días, no semanas).",
  "stability":"Se oxida a GSSG con el oxígeno del aire, y el proceso se acelera con metales traza y con pH alcalino. Es el compuesto del catálogo con la ventana de uso más corta tras reconstituir.",
  "handling":"Riesgo bajo. Olor a azufre característico.",
  "flags":["Uso intravenoso para aclaramiento cutáneo: sin aprobación y con advertencias sanitarias formales emitidas.",
           "El CoA debe reportar la relación GSH/GSSG, no sólo pureza cromatográfica."] },

{ "id":"KP", "name":"KPV", "aka":"Lisina-prolina-valina, α-MSH(11-13)",
  "cls":"Tripéptido antiinflamatorio derivado de α-MSH",
  "cas":"67727-97-3", "formula":"C16H30N4O4", "mw":342.44, "len":3,
  "seq":"Lys-Pro-Val",
  "purpose":"Investigación de inflamación intestinal y cutánea. Es el extremo C-terminal del α-MSH, que conserva la actividad antiinflamatoria sin la pigmentaria.",
  "contains":"Tripéptido sintético liofilizado, sal de acetato. Molécula muy pequeña: 342 Da.",
  "mechanism":"Actúa por vía intracelular más que por receptor de superficie: entra en la célula mediante el transportador de péptidos PepT1 —muy expresado en epitelio intestinal inflamado— e inhibe la translocación nuclear de NF-κB y la activación de NF-κB y AP-1. El resultado es descenso de TNF-α, IL-6 e IL-1β sin activar MC1R, es decir, sin pigmentar.",
  "research":[
    "Reducción de gravedad histológica y de citoquinas en colitis inducida por DSS y por TNBS (ratón).",
    "Actividad antimicrobiana directa frente a Candida albicans y Staphylococcus aureus in vitro.",
    "Reducción de inflamación en modelos de dermatitis (ratón).",
    "Sin ensayos clínicos en humano publicados."],
  "halflife":"Corta.",
  "recon":"Agua bacteriostática. Muy soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Muy buena. Sin cisteína, sin metionina, sin residuos lábiles. Es de los péptidos más robustos del catálogo.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria. Sin datos en humano."] },

{ "id":"OT", "name":"Oxytocin", "aka":"Oxitocina, Pitocin, Syntocinon",
  "cls":"Nonapéptido cíclico neurohipofisario",
  "cas":"50-56-6", "formula":"C43H66N12O12S2", "mw":1007.19, "len":9,
  "seq":"Cys-Tyr-Ile-Gln-Asn-Cys-Pro-Leu-Gly-NH2, ciclado por puente disulfuro Cys1-Cys6",
  "purpose":"Hormona endógena del hipotálamo. Investigación de conducta social, vínculo y contracción uterina.",
  "contains":"Nonapéptido cíclico sintético, liofilizado. Fue el primer péptido en ser secuenciado y sintetizado químicamente (du Vigneaud, Premio Nobel 1955): es el péptido con la historia analítica más larga del catálogo.",
  "mechanism":"Agonista del receptor de oxitocina, acoplado a Gq. En periferia contrae músculo liso uterino y mioepitelio mamario; en el sistema nervioso central modula circuitos de amígdala relacionados con confianza, reconocimiento social y vínculo. La oxitocina periférica cruza mal la barrera hematoencefálica, lo que explica el uso de la vía intranasal en la investigación conductual.",
  "research":[
    "Aprobada por la FDA para inducción del parto y control de hemorragia posparto. Farmacología obstétrica exhaustivamente caracterizada.",
    "Efectos sobre cognición social en humano (intranasal): la literatura inicial fue optimista y la replicación posterior ha sido irregular. Es un caso de manual de crisis de replicación.",
    "Ensayos en autismo: resultados negativos en el estudio multicéntrico grande (fase 2, 2021).",
    "Riesgo real de hiponatremia por actividad antidiurética cruzada sobre el receptor de vasopresina a dosis altas."],
  "halflife":"~3–5 min intravenosa. Muy corta.",
  "recon":"Agua bacteriostática. Soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, uso a corto plazo.",
  "stability":"El puente disulfuro se baraja a pH alcalino y en presencia de reductores. La oxitocina en solución es conocida por su tendencia a formar dímeros y a adsorberse a superficies de vidrio y plástico — un fenómeno documentado que hace perder título sin que aparezca ninguna impureza en el cromatograma.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Existe versión aprobada por FDA; el material de investigación NO es ese producto.",
           "Actividad uterotónica potente: exposición inadvertida en embarazo es un riesgo real.",
           "Riesgo de hiponatremia a dosis altas o con carga hídrica."] },
]


LONGEVITY = [

{ "id":"ET", "name":"Epithalon", "aka":"Epitalón, Epithalamin, AEDG",
  "cls":"Tetrapéptido bioregulador (escuela de Khavinson)",
  "cas":"307297-39-8", "formula":"C14H22N4O9", "mw":390.35, "len":4,
  "seq":"Ala-Glu-Asp-Gly",
  "purpose":"El compuesto insignia de la línea LONGEVITY. Investigación de telomerasa, ritmo circadiano y envejecimiento.",
  "contains":"Tetrapéptido sintético liofilizado, sal de acetato. Molécula muy pequeña (390 Da): un vial de 50 MG contiene una cantidad molar enorme comparada con los péptidos grandes del catálogo.",
  "mechanism":"Fragmento sintético de la epitalamina, extracto de glándula pineal. La hipótesis de Khavinson es que los péptidos cortos se unen directamente al surco menor del ADN en secuencias específicas y modulan la transcripción — un mecanismo epigenético sin receptor de membrana. Se ha descrito inducción de expresión de la subunidad catalítica de la telomerasa (hTERT).",
  "research":[
    "Elongación de telómeros y superación del límite de Hayflick en fibroblastos humanos en cultivo (Khavinson et al.).",
    "Aumento de esperanza de vida en varias cepas de roedor y reducción de incidencia tumoral espontánea (rata, ratón).",
    "Normalización del ritmo de melatonina en humanos mayores (estudios rusos).",
    "Seguimiento observacional de 6–12 años con reducción de mortalidad reportada en cohortes rusas.",
    "ADVERTENCIA METODOLÓGICA: prácticamente toda la evidencia procede de un único grupo de investigación, publicada mayoritariamente en revistas rusas, y no ha sido replicada de forma independiente por terceros. Esto no la invalida, pero define su peso."],
  "halflife":"Muy corta en plasma (minutos). El mecanismo propuesto es transcripcional y no requiere exposición sostenida.",
  "recon":"Agua bacteriostática. Muy soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Muy buena. Sin cisteína ni metionina. Los residuos Asp-Gly pueden formar succinimida lentamente a pH neutro-alcalino, la única ruta de degradación relevante.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria fuera de Rusia.",
           "Evidencia de un solo grupo de investigación, sin replicación independiente.",
           "La activación de telomerasa tiene implicaciones oncológicas teóricas que no han sido evaluadas en humano a largo plazo."] },

{ "id":"NJ", "name":"NAD+", "aka":"Nicotinamida adenina dinucleótido",
  "cls":"Coenzima de dinucleótido (no es un péptido)",
  "cas":"53-84-9", "formula":"C21H27N7O14P2", "mw":663.43, "len":None,
  "seq":"No aplica. Dinucleótido de nicotinamida y adenina unidos por un puente pirofosfato.",
  "purpose":"Investigación de metabolismo energético y de longevidad. Es el sustrato obligado de las sirtuinas y de las PARP.",
  "contains":"Coenzima en forma oxidada (NAD+), liofilizada. Higroscópica. Las presentaciones de 500 y 1000 MG reflejan que el uso investigado es de escala de cientos de miligramos.",
  "mechanism":"Acarreador central de electrones de la glucólisis, el ciclo de Krebs y la beta-oxidación. Además es sustrato consumible —no cofactor reciclado— de las sirtuinas (SIRT1-7), de las PARP de reparación de ADN y de la CD38. Los niveles tisulares descienden con la edad, en buena medida por aumento de la actividad de CD38.",
  "research":[
    "El descenso de NAD+ con la edad está bien documentado en múltiples tejidos y especies.",
    "Restauración de función mitocondrial y de capacidad de ejercicio en ratón envejecido mediante precursores (NR, NMN).",
    "Ensayos humanos con precursores orales elevan NAD+ sanguíneo de forma consistente, pero los resultados funcionales han sido en general modestos o nulos.",
    "La molécula de NAD+ intacta es demasiado grande y polar para atravesar bien la membrana celular: la mayoría de la investigación seria usa precursores (nicotinamida ribósido, NMN), no NAD+ directo. Éste es el punto técnico más importante de la ficha.",
    "La infusión intravenosa de NAD+ es una práctica de clínica privada sin ensayos controlados que la respalden."],
  "halflife":"Corta en circulación; se degrada rápidamente a nicotinamida por NAD-glicohidrolasas.",
  "recon":"Agua bacteriostática o agua estéril. Muy soluble. La solución debe ser incolora o levemente amarilla.",
  "storage":"Liofilizado: −20 °C, sellado y seco. Muy higroscópico. Reconstituido: 2–8 °C, uso a corto plazo.",
  "stability":"Inestable en solución, y particularmente a pH alcalino, donde se degrada en horas. El enlace pirofosfato es el punto lábil. Amarilleamiento marcado indica degradación avanzada.",
  "handling":"Riesgo bajo.",
  "flags":["Sin aprobación regulatoria para uso parenteral.",
           "Biodisponibilidad celular pobre de la molécula intacta comparada con sus precursores.",
           "No es un péptido: requiere métodos analíticos propios (HPLC de intercambio iónico o fase reversa con par iónico)."] },

{ "id":"F4", "name":"FOXO4-DRI", "aka":"FOXO4 D-Retro-Inverso, péptido senolítico",
  "cls":"Péptido senolítico de D-aminoácidos en secuencia retro-inversa",
  "cas":"2460055-10-9", "formula":None, "mw":4826.5, "len":None,
  "seq":"Secuencia retro-inversa completa: todos los residuos son D-aminoácidos y el orden está invertido respecto al péptido nativo. Incluye un dominio de penetración celular fusionado.",
  "purpose":"Investigación de senolisis: eliminación selectiva de células senescentes. Es el compuesto más experimental del catálogo.",
  "contains":"Péptido sintético íntegramente de D-aminoácidos, liofilizado. Su masa (~4826 Da) lo sitúa entre los más grandes de la línea.",
  "mechanism":"La célula senescente mantiene p53 secuestrado en el núcleo por FOXO4, lo que le impide disparar apoptosis y la deja viva pero disfuncional, secretando el fenotipo secretor asociado a senescencia. FOXO4-DRI compite por el sitio de unión, libera p53 y permite que la célula senescente ejecute la apoptosis que tenía bloqueada. La construcción retro-inversa —D-aminoácidos en orden invertido— preserva la topología de las cadenas laterales y hace la molécula prácticamente inmune a las proteasas, que sólo reconocen L-aminoácidos.",
  "research":[
    "Reducción de marcadores de senescencia, restauración de densidad de pelaje, de función renal y de resistencia al ejercicio en ratón envejecido y en ratón progeroide XpdTTD (Baar et al., Cell 2017). Es el estudio fundacional.",
    "Eliminación selectiva de condrocitos senescentes en cultivo humano expandido in vitro.",
    "NO existen ensayos clínicos en humano. Ninguno.",
    "El mecanismo es proapoptótico: la selectividad depende por completo de que la célula sana no dependa del secuestro FOXO4-p53, lo cual es cierto en los modelos estudiados pero no ha sido verificado en humano."],
  "halflife":"Prolongada respecto a un péptido L equivalente por la resistencia a proteasas; no caracterizada en humano.",
  "recon":"Agua bacteriostática o solución salina. Soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, uso a corto plazo.",
  "stability":"Excepcional frente a degradación enzimática, por construcción.",
  "handling":"Péptido proapoptótico. Manejar con guantes y evitar aerosoles. Desechar como residuo químico.",
  "flags":["Sin aprobación regulatoria. Sin ningún dato en humano.",
           "Mecanismo proapoptótico: la selectividad no está verificada en humano.",
           "Es el compuesto del catálogo con la mayor distancia entre entusiasmo de mercado y evidencia disponible.",
           "Un péptido de D-aminoácidos exige confirmación de configuración: la HPLC quiral o el análisis de aminoácidos tras hidrólisis son los únicos métodos que distinguen D de L. Un CoA que sólo reporte masa y pureza NO demuestra que el material sea retro-inverso."] },

{ "id":"DX", "name":"Dihexa", "aka":"N-hexanoil-Tyr-Ile-(6)-aminohexanoil amida, PNB-0408",
  "cls":"Molécula pequeña peptidomimética — análogo de angiotensina IV",
  "cas":"1401708-83-5", "formula":"C27H44N4O5", "mw":504.67, "len":None,
  "seq":"Hexanoil-Tyr-Ile-Ahx-NH2 (Ahx = ácido 6-aminohexanoico). Es un peptidomimético de tres unidades, no un péptido convencional.",
  "purpose":"Investigación de sinaptogénesis y de cognición. La potencia reportada es la razón de su fama y también la razón de la cautela.",
  "contains":"Peptidomimético sintético liofilizado. Lipofílico por la cadena hexanoica, que es lo que le permite cruzar la barrera hematoencefálica.",
  "mechanism":"Potenciador del sistema factor de crecimiento hepatocitario / c-Met. Estabiliza la interacción HGF-Met y amplifica la señalización, lo que en neurona se traduce en formación de nuevas espinas dendríticas y sinapsis funcionales.",
  "research":[
    "Reversión de déficit cognitivo en modelo de escopolamina y en modelo de lesión colinérgica (rata). Reportado como ~7 órdenes de magnitud más potente que el BDNF en ensayos de sinaptogénesis in vitro — una cifra extraordinaria que exige el escrutinio proporcional.",
    "Actividad oral y penetración de barrera hematoencefálica demostradas en roedor.",
    "NO existen ensayos clínicos en humano.",
    "La amplificación de la vía HGF/c-Met tiene implicación oncológica directa: c-Met es un protooncogén y su activación aberrante impulsa varios tumores sólidos. Ningún estudio ha evaluado esta exposición a largo plazo."],
  "halflife":"No caracterizada en humano.",
  "recon":"Poco soluble en agua por la lipofilia. Requiere DMSO u otro codisolvente, seguido de dilución.",
  "storage":"Liofilizado: −20 °C. Solución en DMSO: −20 °C alicuotada.",
  "stability":"Buena como sólido.",
  "handling":"Manejar con guantes. Evitar inhalación.",
  "flags":["Sin aprobación regulatoria. Sin datos en humano.",
           "Activa una vía protooncogénica (c-Met). Riesgo oncológico teórico no evaluado.",
           "La solubilidad acuosa limitada es intrínseca: no es un defecto de lote."] },

{ "id":"DS", "name":"DSIP", "aka":"Delta Sleep-Inducing Peptide, péptido inductor del sueño delta",
  "cls":"Nonapéptido neuromodulador",
  "cas":"62568-57-4", "formula":"C35H48N10O15", "mw":848.8, "len":9,
  "seq":"Trp-Ala-Gly-Gly-Asp-Ala-Ser-Gly-Glu",
  "purpose":"Investigación de arquitectura del sueño y de respuesta al estrés.",
  "contains":"Nonapéptido sintético liofilizado, sal de acetato.",
  "mechanism":"Aislado en 1974 del plasma de conejo sometido a estimulación de sueño delta. Pese a cincuenta años de estudio, NO se ha identificado un receptor propio. Se le atribuye modulación de opioides endógenos, de la liberación de somatostatina y del eje corticotropo. El mecanismo sigue siendo, con honestidad, desconocido.",
  "research":[
    "Aumento de sueño de ondas lentas en conejo y rata, con resultados en humano mucho menos consistentes.",
    "Estudios humanos pequeños en insomnio crónico y en abstinencia de opioides y alcohol, con resultados mixtos.",
    "Efecto antinociceptivo y de reducción de estrés descrito en modelos animales.",
    "La molécula es hidrofílica y su paso de la barrera hematoencefálica es limitado, lo que hace difícil conciliar la vía de administración con el efecto central atribuido.",
    "Sin desarrollo clínico moderno. La literatura es en su mayoría anterior a 1995."],
  "halflife":"Muy corta: minutos en plasma.",
  "recon":"Agua bacteriostática. Soluble.",
  "storage":"Liofilizado: −20 °C protegido de la luz. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"El Trp N-terminal es fotosensible y es también el punto de ataque de las aminopeptidasas. La secuencia Asp-Ala y los Gly-Gly favorecen isomerización lenta.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria.","Mecanismo no establecido tras cinco décadas de estudio.",
           "Literatura mayoritariamente anterior a los estándares metodológicos actuales."] },

{ "id":"PI", "name":"Pinealon", "aka":"EDR, tripéptido Glu-Asp-Arg",
  "cls":"Tripéptido bioregulador (escuela de Khavinson)",
  "cas":"175175-23-2", "formula":"C15H26N6O8", "mw":418.40, "len":3,
  "seq":"Glu-Asp-Arg",
  "purpose":"Investigación de neuroprotección y de regulación circadiana. Derivado de la fracción peptídica de Cortexin.",
  "contains":"Tripéptido sintético liofilizado, sal de acetato.",
  "mechanism":"Mismo marco conceptual que Epithalon: unión directa a secuencias específicas del ADN y modulación de la expresión génica neuronal, sin receptor de membrana. Se le atribuye regulación de genes de defensa antioxidante y de supervivencia neuronal.",
  "research":[
    "Reducción de muerte neuronal por hipoxia y por estrés oxidativo en cultivo y en rata.",
    "Mejora de parámetros cognitivos en rata envejecida (grupo de Khavinson).",
    "Descrita penetración de barrera hematoencefálica en modelo animal.",
    "MISMA LIMITACIÓN QUE EPITHALON: evidencia esencialmente de un solo grupo, publicada en revistas rusas, sin replicación independiente. Sin ensayos clínicos controlados."],
  "halflife":"Muy corta.",
  "recon":"Agua bacteriostática. Muy soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Buena. El par Asp-Arg admite isomerización lenta.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria fuera de Rusia.",
           "Evidencia de un solo grupo, sin replicación independiente."] },

{ "id":"CTL", "name":"Cartalax", "aka":"AED, tripéptido Ala-Glu-Asp",
  "cls":"Tripéptido bioregulador (escuela de Khavinson)",
  "cas":None, "formula":"C12H19N3O8", "mw":333.3, "len":3,
  "seq":"Ala-Glu-Asp",
  "purpose":"Investigación de cartílago y tejido conectivo. Es el bioregulador de la serie dirigido al condrocito.",
  "contains":"Tripéptido sintético liofilizado, sal de acetato. La presentación única de 20 MG refleja el uso investigado.",
  "mechanism":"Mismo marco que Epithalon y Pinealon: interacción directa con ADN y modulación de la expresión génica, con tropismo declarado por condrocito y fibroblasto musculoesquelético.",
  "research":[
    "Modulación de expresión de genes de matriz cartilaginosa en cultivo de condrocitos (grupo de Khavinson).",
    "Descrito efecto sobre marcadores de senescencia en fibroblasto.",
    "La base de evidencia es la MÁS DELGADA de los tres bioreguladores del catálogo: menos publicaciones que Epithalon o Pinealon, todas del mismo grupo, ninguna réplica independiente, ningún ensayo clínico.",
    "No existe una entrada de registro CAS pública consolidada."],
  "halflife":"Muy corta.",
  "recon":"Agua bacteriostática. Muy soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Buena. Los pares Glu-Asp admiten isomerización lenta.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria fuera de Rusia. Sin CAS público consolidado.",
           "Evidencia mínima, de un solo grupo, sin replicación."] },

{ "id":"Ta1", "name":"Thymosin Alpha-1", "aka":"Timosina α1, Tα1, timalfasina, Zadaxin",
  "cls":"Péptido inmunomodulador tímico",
  "cas":"62304-98-7", "formula":"C129H215N33O55", "mw":3108.3, "len":28,
  "seq":"Ac-Ser-Asp-Ala-Ala-Val-Asp-Thr-Ser-Ser-Glu-Ile-Thr-Thr-Lys-Asp-Leu-Lys-Glu-Lys-Lys-Glu-Val-Val-Glu-Glu-Ala-Glu-Asn (N-acetilada)",
  "purpose":"El inmunomodulador mejor caracterizado del catálogo, con aprobación en más de treinta países.",
  "contains":"Péptido sintético de 28 residuos, N-acetilado, liofilizado con manitol y tampón fosfato.",
  "mechanism":"Agonista de los receptores tipo Toll TLR2 y TLR9 en células dendríticas y macrófagos. Promueve la maduración de células T, aumenta la producción de IL-2 e interferón gamma, restaura la función de células NK y desplaza el balance Th1/Th2 hacia Th1. No es inmunoestimulante indiscriminado: es restaurador de función en inmunidad deprimida.",
  "research":[
    "Aprobado en más de 35 países (Zadaxin) para hepatitis B y C crónicas y como adyuvante de vacunación en inmunodeprimidos. NO aprobado por la FDA en EE. UU.",
    "Reducción de mortalidad en sepsis grave en ensayo controlado chino (fase 2, n=361).",
    "Estudiado durante la pandemia de COVID-19 con señal de recuperación de linfopenia en cohortes observacionales.",
    "Adyuvante en melanoma y en hepatocarcinoma con resultados mixtos.",
    "Perfil de seguridad humano de décadas: es el mejor documentado de la línea LONGEVITY."],
  "halflife":"~2 h.",
  "recon":"Agua estéril o agua bacteriostática. Soluble.",
  "storage":"Liofilizado: 2–8 °C aceptable, −20 °C preferible. Reconstituido: 2–8 °C, usar en 24 h en formato clínico; hasta 14 días en investigación.",
  "stability":"La secuencia es rica en Asp, Asn, Ser y Thr: susceptible a desamidación e isomerización. La N-acetilación protege el extremo N.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Aprobado fuera de EE. UU. (Zadaxin); el material de investigación NO es ese producto.",
           "Inmunomodulador: la exposición en enfermedad autoinmune o en trasplante es un riesgo real."] },

{ "id":"TY", "name":"Thymalin", "aka":"Timalina, extracto polipeptídico tímico",
  "cls":"Complejo polipeptídico de origen bovino (no es una molécula única)",
  "cas":None, "formula":None, "mw":None, "len":None,
  "seq":"No aplica. Es una fracción polipeptídica de masa 1000–10000 Da, no una secuencia definida.",
  "purpose":"Investigación de inmunorestauración. Es un extracto, no un péptido sintético, y esa diferencia gobierna todo su manejo.",
  "contains":"Fracción polipeptídica extraída de timo bovino de ternera. La composición NO es una secuencia definida sino una distribución de masas, y varía entre lotes y entre fabricantes por naturaleza del proceso. Ésta es la advertencia central de la ficha.",
  "mechanism":"Mezcla de péptidos tímicos que restauran la diferenciación de linfocitos T, la relación CD4/CD8 y la producción de citoquinas. No se puede atribuir la actividad a un componente único.",
  "research":[
    "Uso clínico establecido en Rusia y en la antigua URSS desde los años ochenta para inmunodeficiencia secundaria.",
    "Estudios de Khavinson con seguimiento de 6–12 años en población geriátrica, con reducción de mortalidad reportada, especialmente en combinación con Epithalamin.",
    "La literatura es rusa y en su mayoría no está indexada ni replicada fuera de ese ámbito.",
    "Al ser extracto, ningún resultado es estrictamente transferible entre lotes ni entre fabricantes."],
  "halflife":"No caracterizada.",
  "recon":"Solución salina isotónica estéril, según práctica del fabricante ruso. Soluble.",
  "storage":"Liofilizado: 2–8 °C, −20 °C preferible. Reconstituido: usar de inmediato.",
  "stability":"No caracterizada de forma sistemática.",
  "handling":"Producto de origen animal bovino. La trazabilidad del origen y el estatus de EEB del rebaño son requisitos sanitarios reales, no formalismos.",
  "flags":["Producto de ORIGEN ANIMAL BOVINO: riesgo de encefalopatía espongiforme y de carga inmunogénica. Exigir certificado de origen y de estatus EEB.",
           "NO es una molécula definida: no admite especificación de pureza por HPLC en el sentido usual. El control de calidad exige perfil electroforético o cromatográfico comparado con un patrón de referencia del propio fabricante.",
           "Sin aprobación fuera de Rusia y países de la CEI.",
           "Es el único artículo del catálogo cuya identidad NO puede verificarse por masa intacta."] },

{ "id":"SK", "name":"Selank", "aka":"Selanc, TP-7, tuftsina heptapeptídica",
  "cls":"Análogo sintético de tuftsina",
  "cas":"129954-34-3", "formula":"C33H57N11O9", "mw":751.88, "len":7,
  "seq":"Thr-Lys-Pro-Arg-Pro-Gly-Pro",
  "purpose":"Investigación de ansiedad y de modulación inmune sin sedación.",
  "contains":"Heptapéptido sintético liofilizado, sal de acetato. Es la tuftsina (TKPR, un tetrapéptido inmunomodulador endógeno) extendida con Pro-Gly-Pro para estabilizarla.",
  "mechanism":"Modula la expresión de GABA-A y aumenta la concentración de encefalinas al inhibir su degradación por enkefalinasas. Regula BDNF en hipocampo. La extensión Pro-Gly-Pro es el estabilizador: bloquea las peptidasas que degradarían la tuftsina en segundos.",
  "research":[
    "Registrado en Rusia como fármaco ansiolítico desde 2009.",
    "Eficacia comparable a benzodiacepinas en trastorno de ansiedad generalizada en ensayos rusos, SIN sedación, sin dependencia y sin síndrome de abstinencia — que es su argumento central.",
    "Aumento de expresión de BDNF en hipocampo (rata).",
    "Efecto inmunomodulador heredado de la tuftsina.",
    "Los ensayos son rusos y no han sido replicados según estándares occidentales."],
  "halflife":"Corta como péptido libre; la vía intranasal es la habitual en investigación.",
  "recon":"Agua bacteriostática. Muy soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Buena. Sin cisteína ni metionina; las tres prolinas dan rigidez conformacional y resistencia a proteasas.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Registrado únicamente en Rusia. Sin aprobación FDA/EMA.",
           "Evidencia sin replicación independiente occidental."] },

{ "id":"SX", "name":"Semax", "aka":"Semaks, ACTH(4-10) Pro-Gly-Pro",
  "cls":"Análogo sintético de ACTH(4-10)",
  "cas":"80714-61-0", "formula":"C37H51N9O10S", "mw":813.92, "len":7,
  "seq":"Met-Glu-His-Phe-Pro-Gly-Pro",
  "purpose":"Investigación de neuroprotección y de cognición. Es el análogo hermano de Selank, del mismo instituto ruso.",
  "contains":"Heptapéptido sintético liofilizado, sal de acetato. Es el fragmento 4-7 de la ACTH (MEHF) extendido con Pro-Gly-Pro.",
  "mechanism":"Conserva la actividad neurotrópica de la ACTH sin su actividad corticotropa: no estimula la suprarrenal. Aumenta la expresión de BDNF y de NGF en hipocampo, modula los sistemas dopaminérgico y serotoninérgico, e inhibe la degradación de encefalinas. Igual que en Selank, el Pro-Gly-Pro es lo que impide que las peptidasas lo destruyan de inmediato.",
  "research":[
    "Registrado en Rusia desde 1996 para ictus isquémico, encefalopatía y neuropatía óptica.",
    "Mejora de recuperación funcional tras ictus isquémico en ensayos rusos.",
    "Aumento sostenido de BDNF en hipocampo tras administración intranasal (rata).",
    "Efecto nootrópico en sujetos sanos descrito en estudios pequeños.",
    "Los ensayos son rusos y no han sido replicados según estándares occidentales."],
  "halflife":"Corta como péptido libre; la vía intranasal es la habitual y la que se corresponde con la literatura.",
  "recon":"Agua bacteriostática. Soluble.",
  "storage":"Liofilizado: −20 °C protegido de la luz y del aire. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"La metionina N-terminal es oxidable: es la ruta de degradación principal y añade +16 Da visible en LC-MS. La histidina también es susceptible. Proteger de aire y de metales traza.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Registrado únicamente en Rusia. Sin aprobación FDA/EMA.",
           "Oxidación de metionina: exigir en el CoA que la impureza +16 Da esté cuantificada, no sólo la pureza global."] },

{ "id":"ML", "name":"Melatonin", "aka":"Melatonina, N-acetil-5-metoxitriptamina",
  "cls":"Indolamina hormonal (no es un péptido)",
  "cas":"73-31-4", "formula":"C13H16N2O2", "mw":232.28, "len":None,
  "seq":"No aplica. Derivado indólico del triptófano.",
  "purpose":"Hormona pineal del ritmo circadiano. Es el compuesto con historial de uso humano más amplio del catálogo.",
  "contains":"Indolamina sintética en polvo. Molécula pequeña (232 Da), no un péptido.",
  "mechanism":"Agonista de los receptores MT1 y MT2 en el núcleo supraquiasmático, el marcapasos circadiano. MT1 media la reducción del disparo neuronal que promueve el sueño; MT2 media el desplazamiento de fase. Es además un captador directo de radicales libres y ese efecto antioxidante es independiente del receptor.",
  "research":[
    "Reducción de latencia de sueño de ~7 min y aumento de duración total de ~8 min frente a placebo en metaanálisis: efecto real, consistente y de magnitud modesta. La expectativa del público suele exceder con mucho esta cifra.",
    "Eficacia clara en desórdenes de fase circadiana: jet lag, trabajo por turnos, síndrome de fase retrasada. Ahí el efecto es sustancialmente mayor que en insomnio primario.",
    "El momento de administración importa más que la dosis: es un cronobiótico, no un hipnótico.",
    "Efecto antioxidante y de protección mitocondrial documentado en modelos preclínicos a dosis muy superiores a las circadianas.",
    "De venta libre como suplemento en EE. UU.; medicamento de prescripción en la UE, Reino Unido, Australia y Japón."],
  "halflife":"~40–60 min. Corta, lo que explica el diseño de formulaciones de liberación prolongada.",
  "recon":"Poco soluble en agua. Requiere etanol, DMSO o ciclodextrina como codisolvente.",
  "storage":"Polvo: −20 °C protegido de la luz. Marcadamente fotosensible.",
  "stability":"Buena como sólido seco y oscuro. El anillo indólico se degrada con la luz y con la oxidación.",
  "handling":"Riesgo bajo.",
  "flags":["Estatus regulatorio variable por país: suplemento en EE. UU., medicamento de prescripción en la UE y otros.",
           "No es un péptido: métodos analíticos propios.",
           "Solubilidad acuosa limitada: es intrínseco a la molécula."] },

{ "id":"KS", "name":"KissPeptin-10", "aka":"Kisspeptina-10, metastina 45-54, KP-10",
  "cls":"Decapéptido hipotalámico regulador del eje reproductivo",
  "cas":"374675-21-5", "formula":"C63H83N17O14", "mw":1302.45, "len":10,
  "seq":"Tyr-Asn-Trp-Asn-Ser-Phe-Gly-Leu-Arg-Phe-NH2",
  "purpose":"Investigación del eje hipotálamo-hipófisis-gónada. Es el regulador maestro de la pubertad y de la reproducción, descubierto en 2003.",
  "contains":"Decapéptido sintético amidado, liofilizado, sal de acetato. Es el fragmento activo mínimo de la kisspeptina-54.",
  "mechanism":"Agonista del receptor KISS1R (GPR54) en las neuronas GnRH del hipotálamo. Es el disparador obligado de la secreción pulsátil de GnRH: sin señalización kisspeptina no hay pubertad, y las mutaciones de KISS1R causan hipogonadismo hipogonadotropo congénito. Aguas abajo eleva LH y FSH, y con ellas testosterona o estradiol.",
  "research":[
    "Elevación robusta y reproducible de LH y de testosterona en varón sano (humano, fase 1, Imperial College London).",
    "Usada como disparador de maduración ovocitaria en FIV, con menor riesgo de síndrome de hiperestimulación ovárica que hCG (humano, fase 2). Es su aplicación clínica más prometedora.",
    "Investigada en amenorrea hipotalámica y en trastornos del deseo sexual.",
    "Taquifilaxia documentada: la administración continua desensibiliza el receptor y SUPRIME el eje en lugar de estimularlo — exactamente el mismo fenómeno que hace que los agonistas de GnRH se usen para castración química. La pauta pulsátil frente a la continua no es un detalle, es la diferencia entre estimular y suprimir.",
    "Sin aprobación en ninguna jurisdicción."],
  "halflife":"~4 min. Extremadamente corta: es un péptido de señalización pulsátil por diseño.",
  "recon":"Agua bacteriostática. Soluble.",
  "storage":"Liofilizado: −20 °C protegido de la luz. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Contiene Trp (fotosensible) y dos Asn (desamidables). Estabilidad media.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria.",
           "Taquifilaxia: la exposición continua suprime el eje reproductivo en lugar de estimularlo.",
           "Actúa sobre el eje reproductivo completo: la exposición inadvertida tiene consecuencias endocrinas reales."] },

{ "id":"B12", "name":"Vitamin B12", "aka":"Cianocobalamina, metilcobalamina, hidroxocobalamina",
  "cls":"Vitamina — complejo de coordinación de cobalto (no es un péptido)",
  "cas":"68-19-9 (cianocobalamina)", "formula":"C63H88CoN14O14P", "mw":1355.37, "len":None,
  "seq":"No aplica. Corrinoide con cobalto central.",
  "purpose":"Vitamina esencial. Cofactor de la metionina sintasa y de la metilmalonil-CoA mutasa.",
  "contains":"Cobalamina en una de sus formas: ciano, metil o hidroxo. La forma importa: la cianocobalamina es la más estable y barata pero requiere conversión metabólica; la metilcobalamina es la forma coenzimática directa; la hidroxocobalamina tiene la retención tisular más prolongada. El CoA debe indicar cuál contiene el vial.",
  "mechanism":"Cofactor de dos enzimas humanas. La metionina sintasa remetila homocisteína a metionina (interfaz con folato y con el ciclo de metilación); la metilmalonil-CoA mutasa procesa propionil-CoA en mitocondria. La deficiencia produce anemia megaloblástica y degeneración combinada subaguda de la médula espinal, que es irreversible si se retrasa el tratamiento.",
  "research":[
    "Farmacología y clínica completamente establecidas. Aprobada por la FDA para deficiencia de B12 y anemia perniciosa.",
    "La corrección de la deficiencia es inequívocamente eficaz. La suplementación en sujetos con niveles normales no mejora energía, cognición ni rendimiento (metaanálisis).",
    "La hidroxocobalamina en dosis alta es antídoto aprobado para intoxicación por cianuro.",
    "Toxicidad prácticamente nula: el exceso se elimina por orina. No se ha establecido nivel superior de ingesta tolerable."],
  "halflife":"Depende de la forma y de la unión a transcobalamina; las reservas hepáticas duran años.",
  "recon":"Muy soluble. La solución es de un rojo intenso característico.",
  "storage":"2–8 °C protegido de la luz. MARCADAMENTE fotosensible: la degradación por luz es rápida y visible como pérdida del color rojo.",
  "stability":"Buena en oscuridad y a pH neutro. Se degrada con luz, con ácido ascórbico y a pH extremo.",
  "handling":"Riesgo muy bajo.",
  "flags":["Existe versión aprobada por FDA; el material de investigación NO es ese producto.",
           "Fotosensibilidad extrema: la pérdida de color rojo es un indicador visual directo de degradación.",
           "No es un péptido."] },
]
