# -*- coding: utf-8 -*-
"""
PEPTIDEX — base de datos técnica de compuestos.  Parte A: FITNESS.

Cada ficha se escribe con la misma disciplina que una hoja de datos de proveedor
analítico: primero la identidad química (que es verificable y no opina), después
la farmacología, y sólo al final el manejo.  Los campos que no tienen una entrada
de registro pública quedan en None y la ficha lo dice — un guión honesto vale más
que un número inventado en un documento que va a acompañar producto.

  seq        secuencia en código de una letra, o descripción si no es un péptido
             lineal estándar
  mw         masa monoisotópica/promedio en Da del ácido libre, salvo nota
  contains   qué hay realmente dentro del vial, que casi nunca es sólo el péptido
  research   hallazgos publicados, con el modelo entre paréntesis — la distinción
             entre roedor y humano es la información más importante de la ficha
  flags      advertencias que deben viajar con el compuesto
"""

FITNESS = [

{ "id":"BC", "name":"BPC-157", "aka":"Body Protection Compound 157, PL 14736, Bepecin",
  "cls":"Pentadecapéptido gástrico",
  "cas":"137525-51-0", "formula":"C62H98N16O22", "mw":1419.53, "len":15,
  "seq":"GEPPPGKPADDAGLV",
  "purpose":"Investigación de reparación tisular: tendón, ligamento, músculo, mucosa gastrointestinal y anastomosis. Es el compuesto más pedido de la línea y también el que más se malinterpreta.",
  "contains":"BPC-157 liofilizado como sal de acetato. Contenido neto de péptido típico 80–90 % de la masa del vial; el resto es contraión, agua residual y manitol si el fabricante usa agente de carga.",
  "mechanism":"Fragmento parcial de una proteína protectora del jugo gástrico humano. En modelos animales regula al alza el receptor VEGFR2 y la vía FAK–paxilina, promueve angiogénesis en el sitio de lesión, e interactúa con el sistema óxido nítrico y con la vía dopaminérgica y serotoninérgica. No se ha identificado un receptor propio.",
  "research":[
    "Aceleración de la cicatrización de tendón de Aquiles seccionado y de ligamento colateral medial (rata).",
    "Protección de mucosa gástrica e intestinal frente a AINEs y alcohol (rata, ratón).",
    "Aceleración de cierre de anastomosis colónica y de fístulas (rata).",
    "Contrarresta el síndrome de abstinencia y la discinesia inducida por haloperidol (rata).",
    "Estable en jugo gástrico humano durante más de 24 h in vitro — la base del interés por vía oral."],
  "halflife":"No caracterizada en humano. En rata la vida media plasmática es de minutos; el efecto observado excede con mucho la exposición plasmática, lo que sugiere acción local.",
  "recon":"Agua bacteriostática o agua estéril para inyección. Muy soluble. Dirigir el chorro a la pared del vial, no sobre la torta liofilizada.",
  "storage":"Liofilizado: −20 °C protegido de la luz, estable años. Reconstituido: 2–8 °C, usar dentro de 20–30 días.",
  "stability":"Notablemente estable para un péptido de 15 residuos: no tiene cisteína, ni metionina, ni puentes disulfuro que oxidar. Los pares Asp-Ala y Asp-Asp son el punto débil (isomerización lenta a pH ácido).",
  "handling":"Sin datos de toxicidad aguda publicados. Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria en ninguna jurisdicción.",
           "Prohibido por la AMA/WADA desde 2022 (clase S0, sustancias no aprobadas)."] },

{ "id":"TB", "name":"TB-500", "aka":"Timosina β4 fragmento 17-23 (Ac-LKKTETQ)",
  "cls":"Fragmento peptídico de timosina β4",
  "cas":"885340-08-9 (fragmento acetilado)", "formula":"C37H65N9O14", "mw":872.0, "len":7,
  "seq":"Ac-LKKTETQ-OH",
  "purpose":"Investigación de migración celular y remodelado de matriz extracelular: tendón, miocardio, córnea y piel.",
  "contains":"Nomenclatura ambigua en el mercado. Lo que se vende como «TB-500» es casi siempre el heptapéptido acetilado LKKTETQ, no la timosina β4 completa (43 residuos, MW 4963). Los viales PEPTIDEX se surten como el fragmento; el certificado de análisis debe confirmar la masa 872 Da y no 4963 Da.",
  "mechanism":"La región LKKTETQ es el sitio de unión a G-actina de la timosina β4. Secuestra monómeros de actina y modula la polimerización del citoesqueleto, lo que en modelos animales se traduce en mayor migración de células endoteliales y de fibroblastos hacia la herida.",
  "research":[
    "Timosina β4 completa acelera reparación cardíaca tras infarto y reactiva progenitores epicárdicos (ratón).",
    "Reduce inflamación y acelera cierre en úlcera corneal (conejo, ensayo humano fase 2 para ojo seco).",
    "Mejora resistencia a la tracción en tendón lesionado (caballo, rata).",
    "El fragmento LKKTETQ reproduce parte de la actividad promigratoria in vitro, con potencia menor que la proteína completa."],
  "halflife":"Fragmento: minutos en plasma. Timosina β4 completa: ~2 h.",
  "recon":"Agua bacteriostática. Soluble; el heptapéptido más que la proteína completa.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Sin cisteína ni metionina. La Thr y la Gln del extremo C son susceptibles de desamidación lenta.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria.",
           "Prohibido por la AMA/WADA (S2, factores de crecimiento).",
           "Verificar en el CoA si el vial contiene fragmento o proteína completa: son compuestos distintos."] },

{ "id":"BB", "name":"BPC-157 + TB-500", "aka":"Blend de reparación",
  "cls":"Mezcla liofilizada de dos péptidos",
  "cas":None, "formula":None, "mw":None, "len":None,
  "seq":"GEPPPGKPADDAGLV  +  Ac-LKKTETQ-OH",
  "purpose":"Presentación combinada de los dos compuestos de reparación más solicitados, coliofilizados en un solo vial.",
  "contains":"Proporción declarada por lote — típicamente 1:1 en masa. Un vial de 10 MG contiene por tanto ~5 mg de cada componente, no 10 mg de cada uno. Este punto es la causa más frecuente de error de cálculo del cliente y debe leerse en la etiqueta.",
  "mechanism":"Ver las fichas individuales. No hay datos publicados de sinergia entre ambos; la combinación es una conveniencia de formulación, no un hallazgo farmacológico.",
  "research":["No existe literatura sobre la mezcla como tal. Toda la evidencia disponible corresponde a cada compuesto por separado."],
  "halflife":"Ver fichas individuales.",
  "recon":"Agua bacteriostática. Ambos componentes son solubles; una sola reconstitución sirve para los dos.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Limitada por el componente menos estable de los dos.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria.","Ambos componentes prohibidos por la AMA/WADA.",
           "El CoA debe reportar pureza y proporción de CADA componente por separado."] },

{ "id":"IG", "name":"IGF-1 LR3", "aka":"Long R3 IGF-1, Mecasermina análoga",
  "cls":"Análogo recombinante de factor de crecimiento (proteína, 83 aa)",
  "cas":"946870-92-4", "formula":"C400H625N111O115S9", "mw":9111.0, "len":83,
  "seq":"Análogo de IGF-1 humano: Arg en posición 3 (sustituye Glu) y extensión N-terminal de 13 residuos.",
  "purpose":"Investigación de señalización anabólica e hipertrofia. Es el único producto de la línea que es una proteína recombinante y no un péptido sintético, con todo lo que eso implica en manejo.",
  "contains":"Proteína recombinante expresada en E. coli, liofilizada con agente de carga (típicamente manitol o trehalosa) y a veces ácido acético residual. El contenido neto de proteína puede ser muy inferior a la masa del vial.",
  "mechanism":"Agonista del receptor IGF-1R. Las dos modificaciones respecto al IGF-1 nativo reducen ~100 veces su afinidad por las proteínas transportadoras IGFBP, de modo que la fracción libre y la vida media efectiva aumentan mucho. Activa PI3K–Akt–mTOR y la vía MAPK.",
  "research":[
    "Aumento de síntesis proteica y de peso de músculo esquelético (rata, ratón).",
    "Uso industrial extendido como suplemento de medio de cultivo celular en biomanufactura, por su resistencia a IGFBP.",
    "IGF-1 nativo (mecasermina) está aprobado por la FDA para deficiencia primaria grave de IGF-1; el análogo LR3 no lo está."],
  "halflife":"~20–30 h en circulación (frente a ~12–15 h del IGF-1 unido a IGFBP-3 y minutos del IGF-1 libre).",
  "recon":"NO usar agua bacteriostática sola: la proteína precipita a pH neutro. Reconstituir con ácido acético 0.01 N o con el diluyente que indique el CoA, y diluir después. Nunca agitar — agitar una proteína la desnaturaliza en la interfase aire-líquido.",
  "storage":"Liofilizado: −20 °C o −80 °C. Reconstituido: 2–8 °C máximo 14 días, o alicuotado a −20 °C. Evitar ciclos de congelación-descongelación.",
  "stability":"Mucho menos robusta que un péptido sintético. Tres puentes disulfuro que se pueden barajar, agregación dependiente de concentración y de agitación.",
  "handling":"Factor de crecimiento mitogénico. Manejar con guantes; evitar aerosoles.",
  "flags":["Sin aprobación regulatoria en esta forma análoga.",
           "Prohibido por la AMA/WADA (S2).",
           "Requiere cadena de frío real. Es el producto del catálogo con mayor riesgo de llegar inactivo."] },

{ "id":"IPA", "name":"Ipamorelin", "aka":"NNC 26-0161",
  "cls":"Secretagogo de GH — agonista del receptor de grelina (GHS-R1a)",
  "cas":"170851-70-4", "formula":"C38H49N9O5", "mw":711.85, "len":5,
  "seq":"Aib-His-D-2-Nal-D-Phe-Lys-NH2",
  "purpose":"Investigación de liberación pulsátil de hormona de crecimiento con mínima señal colateral. Es el secretagogo más selectivo del catálogo.",
  "contains":"Pentapéptido sintético liofilizado, sal de acetato. Contiene tres residuos no proteinogénicos (Aib, D-2-naftilalanina, D-fenilalanina) que son los que le dan resistencia a proteasas.",
  "mechanism":"Agonista selectivo del GHS-R1a en hipófisis e hipotálamo. A diferencia de GHRP-2 y GHRP-6, no eleva de forma apreciable ACTH, cortisol ni prolactina en el rango de dosis estudiado — ésa es toda su razón de ser.",
  "research":[
    "Liberación de GH dependiente de dosis sin elevación de ACTH ni cortisol (rata, cerdo, humano fase 1).",
    "Ausencia del efecto orexigénico marcado que caracteriza a GHRP-6.",
    "Desarrollo clínico interrumpido en fase 2 para íleo postoperatorio, no por seguridad sino por resultado insuficiente."],
  "halflife":"~2 h.",
  "recon":"Agua bacteriostática. Muy soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Buena. Sin cisteína ni metionina; la amidación C-terminal bloquea la exopeptidasa.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria.","Prohibido por la AMA/WADA (S2)."] },

{ "id":"CD", "name":"CJC-1295 (DAC)", "aka":"CJC-1295 con Drug Affinity Complex, DAC:GRF",
  "cls":"Análogo de GHRH con conjugación a albúmina",
  "cas":"863288-34-0", "formula":"C165H269N47O46", "mw":3647.15, "len":30,
  "seq":"YaDAIFTQSYRKVLAQLSARKLLQDILSR-NH2 con linker maleimidopropionil en el extremo C (a = D-Ala)",
  "purpose":"Investigación de elevación sostenida de GH e IGF-1 durante días, en lugar de pulsos.",
  "contains":"Análogo de GHRH(1-29) con cuatro sustituciones (D-Ala2, Gln8, Ala15, Leu27) más el linker DAC. Liofilizado como sal de acetato.",
  "mechanism":"Agonista del receptor de GHRH. Las cuatro sustituciones bloquean la degradación por DPP-4 y la isomerización de Asp; el grupo maleimida del DAC forma un enlace covalente con la Cys34 de la albúmina sérica al inyectarse, lo que arrastra la vida media de minutos a días.",
  "research":[
    "Elevación sostenida de GH (2–10×) e IGF-1 (1.5–3×) durante hasta 6 días tras dosis única (humano, fase 1).",
    "Efecto acumulativo con dosis semanales múltiples (humano, fase 1).",
    "El desarrollo se detuvo tras una muerte en un ensayo con un compuesto relacionado de la misma compañía; la relación causal nunca se estableció públicamente."],
  "halflife":"~6–8 días.",
  "recon":"Agua bacteriostática. Soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, hasta 30 días.",
  "stability":"Buena en liofilizado. El grupo maleimida es hidrolizable: una vez en solución pierde capacidad de conjugación con el tiempo, aunque el péptido siga íntegro. Es un caso donde HPLC puede decir «puro» y el producto ya no funcionar como DAC.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria.","Prohibido por la AMA/WADA (S2).",
           "Confusión de mercado constante: mucho producto etiquetado «CJC-1295» es en realidad la versión SIN DAC (Modified GRF 1-29). Verificar masa 3647 Da en el CoA."] },

{ "id":"CN", "name":"CJC-1295 (no DAC)", "aka":"Modified GRF (1-29), Mod-GRF 1-29, Sermorelin tetrasustituido",
  "cls":"Análogo de GHRH sin conjugación",
  "cas":"863288-34-0 (mismo esqueleto peptídico)", "formula":"C152H252N44O42", "mw":3367.9, "len":29,
  "seq":"YaDAIFTQSYRKVLAQLSARKLLQDILSR-NH2 (a = D-Ala), sin linker DAC",
  "purpose":"Investigación de pulsos de GH con perfil fisiológico, habitualmente en co-administración con un agonista de grelina.",
  "contains":"Mismas cuatro sustituciones que la versión DAC, sin el linker. Liofilizado como sal de acetato.",
  "mechanism":"Agonista del receptor de GHRH. Sin DAC no hay unión a albúmina, de modo que la acción es un pulso de ~30 minutos que imita la secreción endógena en lugar de sostenerla.",
  "research":[
    "Pico de GH a los 15–30 min y retorno a basal antes de 2 h (humano).",
    "Efecto sinérgico documentado al combinarlo con un agonista de GHS-R1a: las dos vías son independientes y se potencian.",
    "Sermorelin (GHRH 1-29 sin modificar) sí tuvo aprobación FDA, retirada del mercado en 2008 por motivos comerciales."],
  "halflife":"~30 min.",
  "recon":"Agua bacteriostática. Soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Buena. Más estable que sermorelin nativo, que es precisamente lo que buscaban las sustituciones.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria.","Prohibido por la AMA/WADA (S2).",
           "Distinguir de la versión DAC: masa 3368 Da frente a 3647 Da."] },

{ "id":"CP", "name":"CJC-1295 + Ipamorelin", "aka":"Blend GHRH + GHS",
  "cls":"Mezcla liofilizada de análogo de GHRH y secretagogo",
  "cas":None, "formula":None, "mw":None, "len":None,
  "seq":"Mod-GRF(1-29)  +  Aib-His-D-2-Nal-D-Phe-Lys-NH2",
  "purpose":"La combinación con más fundamento farmacológico del catálogo: dos receptores distintos que convergen sobre la misma célula somatótropa.",
  "contains":"Proporción declarada por lote, habitualmente 1:1 en masa. Un vial de 10 MG lleva ~5 mg de cada uno. Verificar en etiqueta antes de calcular.",
  "mechanism":"El análogo de GHRH aumenta la amplitud del pulso; el agonista de grelina aumenta la frecuencia y suprime somatostatina. Al actuar sobre receptores independientes, el efecto combinado supera la suma de los aislados — esto sí está documentado, a diferencia de la mezcla BPC+TB.",
  "research":[
    "Sinergia GHRH + GHRP demostrada de forma reproducible en humano desde los años noventa (prueba combinada GHRH-arginina y GHRH-GHRP como test diagnóstico de reserva hipofisaria).",
    "La combinación específica CJC/Ipamorelin no tiene ensayos propios publicados."],
  "halflife":"~30 min (GHRH) y ~2 h (Ipamorelin).",
  "recon":"Agua bacteriostática. Ambos solubles.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Buena para ambos componentes.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria.","Ambos componentes prohibidos por la AMA/WADA (S2).",
           "El CoA debe reportar pureza y proporción de cada componente."] },

{ "id":"SMO", "name":"Sermorelin", "aka":"GHRH (1-29), GRF (1-29), Geref",
  "cls":"Fragmento activo de GHRH humano",
  "cas":"86168-78-7", "formula":"C149H246N44O42S", "mw":3357.9, "len":29,
  "seq":"YADAIFTNSYRKVLGQLSARKLLQDIMSR-NH2",
  "purpose":"Investigación del eje somatotropo. Es la secuencia nativa, sin modificar — el punto de comparación frente al cual se diseñaron CJC-1295 y tesamorelina.",
  "contains":"Los 29 primeros residuos del GHRH humano de 44 residuos, amidados en C. Liofilizado, habitualmente con manitol.",
  "mechanism":"Agonista del receptor de GHRH en hipófisis anterior. Conserva la actividad completa del GHRH de 44 residuos: los 15 residuos restantes no aportan potencia.",
  "research":[
    "Aprobado por la FDA (Geref) como prueba diagnóstica de reserva de GH y para deficiencia de GH pediátrica. Retirado del mercado estadounidense en 2008 por decisión comercial del fabricante, no por seguridad — un dato que conviene tener claro.",
    "Perfil de seguridad humano bien caracterizado, cosa que casi ningún compuesto de esta lista puede decir.",
    "Preserva la retroalimentación por somatostatina, de modo que no anula el eje."],
  "halflife":"~11–12 min. Sustrato de DPP-4, que es exactamente lo que corrigieron las sustituciones del Mod-GRF.",
  "recon":"Agua bacteriostática o agua estéril. Soluble.",
  "storage":"Liofilizado: 2–8 °C aceptable, −20 °C preferible. Reconstituido: 2–8 °C, usar en 14 días.",
  "stability":"La Met27 es oxidable y la Asn8 desamida. Menos robusto que sus análogos modificados.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Producto histórico aprobado; la presentación actual como material de investigación no lo está.",
           "Prohibido por la AMA/WADA (S2)."] },

{ "id":"TSM", "name":"Tesamorelin", "aka":"TH9507, Egrifta",
  "cls":"Análogo estabilizado de GHRH (1-44)",
  "cas":"218949-48-5", "formula":"C221H366N72O67S", "mw":5135.9, "len":44,
  "seq":"GHRH(1-44) humano con grupo trans-3-hexenoil en el N-terminal",
  "purpose":"El único compuesto de la línea FITNESS con aprobación FDA vigente para una indicación de composición corporal.",
  "contains":"GHRH humano completo de 44 residuos, N-acilado. Liofilizado con manitol.",
  "mechanism":"Agonista del receptor de GHRH. El grupo hexenoil en el N-terminal bloquea el corte por DPP-4 sin alterar la unión al receptor, lo que multiplica la vida media respecto a sermorelin.",
  "research":[
    "Reducción de 15–18 % de tejido adiposo visceral frente a placebo en dos ensayos fase 3 en lipodistrofia asociada a VIH (humano, n>800). Aprobado por la FDA en 2010 como Egrifta.",
    "Reducción de triglicéridos y mejora del perfil lipídico en la misma población.",
    "Señal de mejora cognitiva en adultos mayores con deterioro leve (ensayo pequeño).",
    "El efecto sobre grasa visceral es selectivo: no reduce grasa subcutánea de forma comparable."],
  "halflife":"~26–38 min tras administración subcutánea.",
  "recon":"Agua estéril para inyección. Egrifta comercial se reconstituye con un diluyente específico. Soluble.",
  "storage":"Liofilizado: −20 °C (la presentación comercial admite 2–8 °C). Reconstituido: usar de inmediato en formato clínico; 2–8 °C hasta 14 días en investigación.",
  "stability":"Buena en liofilizado. Contiene Met y Asn susceptibles; la formulación con manitol es parte de la estabilización.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Existe una versión aprobada por FDA (Egrifta) para lipodistrofia por VIH; el material de investigación NO es ese producto.",
           "Prohibido por la AMA/WADA (S2)."] },

{ "id":"G2", "name":"GHRP-2", "aka":"Pralmorelin, KP-102",
  "cls":"Secretagogo de GH — agonista de GHS-R1a",
  "cas":"158861-67-7", "formula":"C45H55N9O6", "mw":817.96, "len":6,
  "seq":"D-Ala-D-2-Nal-Ala-Trp-D-Phe-Lys-NH2",
  "purpose":"Investigación de liberación de GH con potencia alta. Aprobado en Japón como agente diagnóstico.",
  "contains":"Hexapéptido sintético liofilizado, sal de acetato.",
  "mechanism":"Agonista de GHS-R1a. Más potente que ipamorelin sobre GH, pero mucho menos selectivo: eleva de forma medible prolactina, ACTH y cortisol.",
  "research":[
    "Aprobado en Japón (GHRP Kaken 100) como prueba diagnóstica de deficiencia de GH en adultos.",
    "Elevación de GH superior a GHRP-6 a dosis equimolares (humano).",
    "Aumento de apetito menor que GHRP-6 pero presente.",
    "Elevación de cortisol y prolactina de ~15–20 % sobre basal a dosis altas (humano)."],
  "halflife":"~30 min.",
  "recon":"Agua bacteriostática. Soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Buena. El Trp es fotosensible: proteger de la luz es una instrucción real, no decorativa.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Aprobado sólo en Japón y sólo como diagnóstico.","Prohibido por la AMA/WADA (S2)."] },

{ "id":"G6", "name":"GHRP-6", "aka":"SKF-110679, Growth Hormone Releasing Hexapeptide",
  "cls":"Secretagogo de GH — agonista de GHS-R1a",
  "cas":"87616-84-0", "formula":"C46H56N12O6", "mw":873.02, "len":6,
  "seq":"His-D-Trp-Ala-Trp-D-Phe-Lys-NH2",
  "purpose":"El secretagogo original. Investigación de GH y, sobre todo, del efecto orexigénico de la vía grelina.",
  "contains":"Hexapéptido sintético liofilizado, sal de acetato.",
  "mechanism":"Agonista de GHS-R1a. Fue el compuesto cuyo estudio llevó al descubrimiento del receptor de grelina y después de la propia grelina — es decir, el fármaco precedió al ligando natural.",
  "research":[
    "Aumento marcado y reproducible del apetito (humano, rata): el más pronunciado de la clase.",
    "Liberación de GH dependiente de dosis (humano).",
    "Elevación de cortisol y prolactina, mayor que ipamorelin.",
    "Efectos citoprotectores cardíacos independientes de GH descritos en modelos de isquemia (rata)."],
  "halflife":"~15–20 min.",
  "recon":"Agua bacteriostática. Soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Dos residuos de triptófano: es el péptido más fotosensible de la línea FITNESS. Vial ámbar o protección de luz obligatoria.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria.","Prohibido por la AMA/WADA (S2)."] },

{ "id":"HX", "name":"Hexarelin", "aka":"Examorelin, EP-23905",
  "cls":"Secretagogo de GH — agonista de GHS-R1a y de CD36",
  "cas":"140703-51-1", "formula":"C47H58N12O6", "mw":887.04, "len":6,
  "seq":"His-D-2-methyl-Trp-Ala-Trp-D-Phe-Lys-NH2",
  "purpose":"Investigación de GH y de cardioprotección. Es el análogo de GHRP-6 metilado en posición 2.",
  "contains":"Hexapéptido sintético liofilizado, sal de acetato.",
  "mechanism":"Agonista de GHS-R1a más potente que GHRP-6, y además ligando de CD36 en tejido cardiovascular — esa segunda vía es la que explica los efectos cardíacos independientes de GH.",
  "research":[
    "Efecto cardioprotector en isquemia-reperfusión, presente incluso en animales hipofisectomizados, lo que prueba que no depende de GH (rata).",
    "Liberación de GH potente pero con desensibilización del receptor documentada tras administración continua (humano): el efecto decae con el uso sostenido.",
    "Elevación de cortisol y prolactina comparable o superior a GHRP-2."],
  "halflife":"~55–70 min.",
  "recon":"Agua bacteriostática. Soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Dos Trp: fotosensible. Proteger de la luz.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria.","Prohibido por la AMA/WADA (S2).",
           "Desensibilización documentada — el único de la clase con esa advertencia explícita en literatura humana."] },

{ "id":"H", "name":"HGH 191AA", "aka":"Somatropina, hormona de crecimiento humana recombinante, rhGH",
  "cls":"Proteína recombinante de 191 aminoácidos",
  "cas":"12629-01-5", "formula":"C990H1528N262O300S7", "mw":22124.0, "len":191,
  "seq":"Secuencia idéntica a la somatropina humana hipofisaria, 191 residuos, dos puentes disulfuro (Cys53-Cys165, Cys182-Cys189).",
  "purpose":"El producto de referencia del eje. Todo lo demás en esta categoría existe para estimular su liberación endógena en lugar de administrarla.",
  "contains":"Proteína recombinante expresada en E. coli, liofilizada con manitol, glicina y fosfato como tampón. Dosificada en Unidades Internacionales: 1 UI ≈ 0.33 mg de proteína. Un vial de 10 UI contiene ~3.3 mg.",
  "mechanism":"Agonista del receptor de GH (dimerización de GHR y señalización JAK2–STAT5). Actúa directamente y también de forma indirecta a través de la producción hepática de IGF-1.",
  "research":[
    "Farmacología humana exhaustivamente caracterizada. Aprobada por la FDA para deficiencia de GH pediátrica y adulta, síndrome de Turner, Prader-Willi, talla baja idiopática, síndrome de intestino corto y caquexia por VIH.",
    "El efecto sobre masa magra es real y dependiente de dosis; el efecto sobre fuerza en adultos sanos es mucho menor de lo que suele suponerse (metaanálisis).",
    "Efectos adversos dependientes de dosis bien documentados: retención hídrica, artralgia, síndrome del túnel carpiano, resistencia a la insulina."],
  "halflife":"~3–4 h subcutánea; el efecto biológico vía IGF-1 dura mucho más.",
  "recon":"Agua bacteriostática, en chorro dirigido a la pared del vial. NUNCA agitar: la agitación desnaturaliza la proteína en la interfase aire-líquido y no hay forma visual de detectarlo.",
  "storage":"Liofilizado: 2–8 °C (algunos fabricantes admiten temperatura ambiente hasta la reconstitución). Reconstituido: 2–8 °C estrictamente, 14–21 días.",
  "stability":"Sensible a calor, agitación, congelación de la solución y luz. Es la molécula más frágil del catálogo junto con IGF-1 LR3.",
  "handling":"Manejar con guantes. La identidad de una somatropina sólo se confirma con masa intacta 22124 Da; la HPLC de fase reversa sola no distingue variantes deamidadas.",
  "flags":["Existe versión aprobada por FDA; el material de investigación NO es ese producto.",
           "Prohibida por la AMA/WADA (S2).",
           "Sustancia controlada a nivel federal en EE. UU. (21 U.S.C. §333(e)): su distribución para usos no aprobados es delito federal. Es el único artículo del catálogo con esa exposición penal específica."] },

{ "id":"RT", "name":"Retatrutide", "aka":"LY3437943",
  "cls":"Triple agonista GIP / GLP-1 / glucagón, lipidado",
  "cas":"2381089-83-2", "formula":"C221H342N46O68", "mw":4731.33, "len":39,
  "seq":"Esqueleto de GIP de 39 residuos con sustituciones optimizadas y cadena de ácido graso C20 diácido en Lys17.",
  "purpose":"Investigación metabólica de última generación. Es el compuesto en desarrollo con mayor magnitud de pérdida de peso reportada en fase 2.",
  "contains":"Péptido sintético lipidado, liofilizado, sal de acetato. Los viales de masa alta (40–60 MG) requieren especial cuidado en el cálculo de concentración.",
  "mechanism":"Agonismo balanceado en tres receptores: GIPR, GLP-1R y GCGR. Los dos primeros actúan sobre saciedad e insulina; el componente glucagón añade gasto energético, que es lo que separa a este compuesto de los agonistas duales. La lipidación permite dosificación semanal por unión a albúmina.",
  "research":[
    "Pérdida de peso media de 24.2 % a 48 semanas con la dosis de 12 mg en fase 2 (humano, n=338) — la cifra más alta publicada para un agente farmacológico.",
    "Reducción de HbA1c comparable a los mejores agonistas duales en diabetes tipo 2 (fase 2).",
    "Fase 3 (programa TRIUMPH) en curso.",
    "Efectos adversos gastrointestinales dependientes de dosis y de velocidad de escalada; aumento leve de frecuencia cardiaca."],
  "halflife":"~6 días. Compatible con administración semanal.",
  "recon":"Agua bacteriostática. Soluble, pero la lipidación hace que se disuelva más lento que un péptido no acilado: dar tiempo, no agitar.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, hasta 30 días.",
  "stability":"Buena. La cadena grasa favorece autoasociación a concentraciones altas — un aspecto opalescente puede ser micelización reversible y no degradación.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["NO aprobado en ninguna jurisdicción. En investigación clínica fase 3.",
           "Producto en investigación activa: la copia sintética no equivale al material de ensayo clínico."] },

{ "id":"SM", "name":"Semaglutide", "aka":"Ozempic, Wegovy, Rybelsus (marcas del innovador)",
  "cls":"Agonista de GLP-1R, lipidado",
  "cas":"910463-68-2", "formula":"C187H291N45O59", "mw":4113.58, "len":31,
  "seq":"Análogo de GLP-1(7-37): Aib8, Arg34, y cadena C18 diácido unida vía espaciador AEEA-AEEA a Lys26.",
  "purpose":"Investigación metabólica. Es el compuesto de referencia contra el que se miden todos los demás de esta categoría.",
  "contains":"Péptido sintético lipidado, liofilizado, sal de acetato. El producto de investigación no es equivalente al medicamento de marca, que incluye fosfato disódico, propilenglicol y fenol como formulación.",
  "mechanism":"Agonista del receptor de GLP-1. Aib8 bloquea DPP-4; la lipidación C18 con espaciador AEEA da unión fuerte a albúmina y vida media de una semana. Reduce ingesta por acción central en hipotálamo y tronco, y enlentece el vaciamiento gástrico.",
  "research":[
    "STEP 1: pérdida de peso media 14.9 % a 68 semanas (humano, n=1961).",
    "SELECT: reducción de 20 % en eventos cardiovasculares mayores en pacientes con obesidad y enfermedad cardiovascular sin diabetes (humano, n=17604).",
    "SUSTAIN: control glucémico superior a otros agonistas de GLP-1 en diabetes tipo 2.",
    "Efectos adversos gastrointestinales frecuentes; señal de riesgo de tumores de células C en roedor, no confirmada en humano."],
  "halflife":"~7 días.",
  "recon":"Agua bacteriostática. Disolución lenta por la lipidación; no agitar.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, hasta 30 días.",
  "stability":"Buena. Autoasocia en heptámeros a concentración alta, lo que es normal y reversible.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Existe versión aprobada por FDA/EMA; el material de investigación NO es ese producto.",
           "Contraindicación de etiqueta del innovador: antecedente personal o familiar de carcinoma medular de tiroides o MEN2.",
           "Producto bajo patente vigente del innovador en la mayoría de jurisdicciones."] },

{ "id":"TR", "name":"Tirzepatide", "aka":"Mounjaro, Zepbound (marcas del innovador), LY3298176",
  "cls":"Doble agonista GIP / GLP-1, lipidado",
  "cas":"2023788-19-2", "formula":"C225H348N48O68", "mw":4813.45, "len":39,
  "seq":"Esqueleto de GIP de 39 residuos con Aib2 y Aib13, amidado en C, y cadena C20 diácido vía doble AEEA en Lys20.",
  "purpose":"Investigación metabólica. El primer doble agonista incretínico que llegó al mercado.",
  "contains":"Péptido sintético lipidado, liofilizado, sal de acetato.",
  "mechanism":"Agonismo dual GIPR/GLP-1R con sesgo hacia GIP. La adición del brazo GIP mejora la tolerabilidad gastrointestinal relativa y añade efecto sobre lipólisis y sensibilidad a insulina en adipocito.",
  "research":[
    "SURMOUNT-1: pérdida de peso media 20.9 % a 72 semanas con 15 mg (humano, n=2539).",
    "SURPASS-2: superioridad frente a semaglutida 1 mg en HbA1c y en peso (humano).",
    "SURMOUNT-OSA: aprobado por FDA en 2024 para apnea obstructiva del sueño en obesidad.",
    "Perfil de efectos adversos gastrointestinales similar al de los agonistas de GLP-1."],
  "halflife":"~5 días.",
  "recon":"Agua bacteriostática. Disolución lenta; no agitar.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, hasta 30 días.",
  "stability":"Buena.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Existe versión aprobada por FDA/EMA; el material de investigación NO es ese producto.",
           "Misma advertencia de carcinoma medular de tiroides que semaglutida.",
           "Producto bajo patente vigente del innovador."] },

{ "id":"MZ", "name":"Mazdutide", "aka":"IBI362, LY3305677, OXM-3",
  "cls":"Doble agonista GLP-1 / glucagón, análogo de oxintomodulina",
  "cas":"2259884-03-0", "formula":"C210H322N46O67", "mw":4563.1, "len":39,
  "seq":"Análogo lipidado de oxintomodulina de 39 residuos.",
  "purpose":"Investigación metabólica. Es la vía oxintomodulina, distinta del esqueleto GIP de retatrutida y tirzepatida.",
  "contains":"Péptido sintético lipidado, liofilizado, sal de acetato.",
  "mechanism":"Agonismo dual GLP-1R/GCGR derivado de la oxintomodulina nativa. El componente glucagón aporta gasto energético y efecto hepático sobre esteatosis; el componente GLP-1 aporta saciedad y control glucémico.",
  "research":[
    "Pérdida de peso de hasta 15.4 % a 48 semanas con 9 mg en población china (fase 2, GLORY-1 y estudios previos).",
    "Reducción marcada de grasa hepática, atribuida al brazo glucagón (fase 2).",
    "Aprobado en China en 2025 para control de peso; sin aprobación en EE. UU. ni UE.",
    "Base de evidencia predominantemente en población asiática, lo que limita la extrapolación."],
  "halflife":"~7–8 días.",
  "recon":"Agua bacteriostática. Disolución lenta; no agitar.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, hasta 30 días.",
  "stability":"Buena.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Aprobado únicamente en China. Sin aprobación FDA/EMA.",
           "Producto en investigación activa fuera de China."] },

{ "id":"CGL", "name":"Cagrilintide", "aka":"AM833, NNC0174-0833",
  "cls":"Análogo de amilina de acción prolongada",
  "cas":"1415456-99-3", "formula":"C194H312N54O59S2", "mw":4409.0, "len":37,
  "seq":"Análogo de amilina humana de 37 residuos con puente disulfuro Cys2-Cys7 y cadena grasa C20.",
  "purpose":"Investigación de saciedad por una vía distinta a las incretinas. Rara vez se estudia solo; su interés está en la combinación.",
  "contains":"Péptido sintético lipidado con un puente disulfuro intramolecular, liofilizado, sal de acetato.",
  "mechanism":"Agonista dual del receptor de amilina (AMY) y del receptor de calcitonina (CTR). La amilina es la hormona cosecretada con insulina por la célula beta; señaliza saciedad en área postrema y enlentece el vaciamiento gástrico por una vía independiente de GLP-1. Ésa independencia es la razón de que combine bien.",
  "research":[
    "Pérdida de peso de 10.8 % a 26 semanas en monoterapia con 4.5 mg (fase 2, humano).",
    "Semivida de eliminación de 159–195 h, compatible con dosificación semanal.",
    "El grueso del desarrollo es como componente de CagriSema."],
  "halflife":"~7–8 días (159–195 h).",
  "recon":"Agua bacteriostática. Disolución lenta.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, hasta 30 días.",
  "stability":"El puente disulfuro Cys2-Cys7 puede barajarse en condiciones reductoras o a pH alcalino. Evitar agentes reductores y pH>8.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["NO aprobado en ninguna jurisdicción. En desarrollo clínico."] },

{ "id":"CS", "name":"Cagri + Sema", "aka":"CagriSema",
  "cls":"Mezcla de análogo de amilina y agonista de GLP-1",
  "cas":None, "formula":None, "mw":None, "len":None,
  "seq":"Cagrilintide  +  Semaglutida",
  "purpose":"La combinación metabólica con más respaldo de ensayo del catálogo. Dos vías de saciedad independientes en un solo vial.",
  "contains":"Proporción declarada por lote; el innovador desarrolla la combinación en relación 1:1 en masa. Un vial de 10 MG contiene ~5 mg de cada componente. Verificar en etiqueta.",
  "mechanism":"Amilina y GLP-1 señalizan saciedad por circuitos distintos que convergen en hipotálamo y tronco encefálico. La combinación produce mayor reducción de ingesta que cualquiera de los dos por separado.",
  "research":[
    "REDEFINE-1: pérdida de peso media 22.7 % a 68 semanas (humano, n=3417), por encima de cada componente en monoterapia.",
    "REDEFINE-2 en diabetes tipo 2 con magnitud menor, como es habitual en esa población.",
    "El resultado quedó por debajo de las expectativas del mercado pese a ser clínicamente sustancial."],
  "halflife":"~7 días ambos componentes.",
  "recon":"Agua bacteriostática. Disolución lenta; no agitar.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, hasta 30 días.",
  "stability":"Limitada por cagrilintida (puente disulfuro).",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["NO aprobado. En desarrollo clínico.",
           "El CoA debe reportar pureza y proporción de cada componente por separado."] },

{ "id":"AD", "name":"AOD-9604", "aka":"hGH fragmento 176-191, Tyr-hGH(177-191)",
  "cls":"Fragmento C-terminal modificado de hormona de crecimiento",
  "cas":"221231-10-3", "formula":"C78H123N23O23S2", "mw":1815.1, "len":16,
  "seq":"Tyr-LRIVQCRSVEGSCGF (residuos 177-191 de hGH con Tyr añadida en N), puente disulfuro Cys182-Cys189.",
  "purpose":"Investigación de lipólisis sin las acciones metabólicas de la GH completa.",
  "contains":"Péptido sintético con un puente disulfuro, liofilizado, sal de acetato.",
  "mechanism":"Reproduce la actividad lipolítica del extremo C-terminal de la GH sin el dominio de unión al receptor de GH: no eleva IGF-1 ni afecta la sensibilidad a la insulina. En adipocito estimula lipólisis e inhibe lipogénesis por una vía β3-adrenérgica en roedor.",
  "research":[
    "Reducción de masa grasa en modelos de obesidad genética y dietética (ratón ob/ob).",
    "Ensayos clínicos fase 2 en obesidad humana: NO alcanzaron el objetivo primario de pérdida de peso. Éste es el dato central de la ficha y suele omitirse en la literatura comercial.",
    "Señal de condroprotección en osteoartritis explorada posteriormente.",
    "Estatus de GRAS negado por la FDA como ingrediente alimentario en 2015."],
  "halflife":"~30 min.",
  "recon":"Agua bacteriostática. Soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"El puente disulfuro puede reducirse o barajarse. Evitar agentes reductores.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria. Falló su objetivo primario en fase 2 humana.",
           "Prohibido por la AMA/WADA (S2)."] },

{ "id":"APT", "name":"Adipotide", "aka":"FTPP, Prohibitin-targeting peptide 1, CKGGRAKDC-GG-D(KLAKLAK)2",
  "cls":"Péptido proapoptótico dirigido a vasculatura de tejido adiposo",
  "cas":None, "formula":"C152H252N44O42", "mw":2611.41, "len":26,
  "seq":"CKGGRAKDC-GG-D(KLAKLAK)2, cíclico por puente disulfuro en el motivo de direccionamiento.",
  "purpose":"Investigación de ablación selectiva de vasculatura adiposa. Es, con diferencia, el compuesto de mecanismo más agresivo del catálogo.",
  "contains":"Péptido quimérico sintético con puente disulfuro, liofilizado. Dos dominios: uno de direccionamiento y uno citotóxico.",
  "mechanism":"El motivo CKGGRAKDC se une a prohibitina expresada en el endotelio de la vasculatura de tejido adiposo blanco. Una vez internalizado, el dominio D(KLAKLAK)2 —un péptido amfipático de D-aminoácidos— rompe la membrana mitocondrial y dispara apoptosis. El resultado es destrucción del aporte vascular al adipocito, no lipólisis.",
  "research":[
    "Reducción de peso de ~30 % con restauración de sensibilidad a insulina en primate obeso (macaco Rhesus), el estudio que lo hizo famoso.",
    "Nefrotoxicidad dependiente de dosis observada en el mismo estudio de primate: cambios degenerativos en túbulo renal, reversibles al suspender.",
    "El desarrollo clínico no avanzó. No existen datos de fase 2 ni de seguridad a largo plazo en humano.",
    "El mecanismo no discrimina entre vasculatura adiposa y otros lechos que expresen prohibitina."],
  "halflife":"Corta, del orden de minutos a una hora.",
  "recon":"Agua bacteriostática o solución salina estéril. Soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, uso a corto plazo.",
  "stability":"Puente disulfuro sensible a reducción — y su apertura destruye el direccionamiento sin destruir el dominio citotóxico, que es el peor escenario posible.",
  "handling":"Péptido citotóxico. Manejar con guantes y protección ocular; evitar cualquier aerosol. Desechar como residuo químico.",
  "flags":["Sin aprobación regulatoria. Sin datos de seguridad en humano.",
           "Nefrotoxicidad documentada en primate.",
           "Mecanismo citotóxico intrínseco: el dominio KLAKLAK mata cualquier célula en la que entre."] },

{ "id":"AM", "name":"5-Amino-1MQ", "aka":"5-amino-1-metilquinolinio",
  "cls":"Molécula pequeña — inhibidor de NNMT (no es un péptido)",
  "cas":"42464-96-0 (sal de yoduro)", "formula":"C10H11N2+ (catión); C10H11IN2 como yoduro", "mw":159.21, "len":None,
  "seq":"No aplica. Es un catión quinolinio de molécula pequeña.",
  "purpose":"Investigación del metabolismo del adipocito por la vía NNMT/NAD+. Se incluye en la línea FITNESS pese a no ser un péptido.",
  "contains":"Sal de yoduro o de cloruro del catión quinolinio, en polvo. Peso molecular de la sal (286.11 para el yoduro) frente al del catión (159.21): confirmar cuál reporta el CoA antes de calcular concentración.",
  "mechanism":"Inhibidor competitivo de la nicotinamida N-metiltransferasa, la enzima citosólica que metila nicotinamida a 1-metilnicotinamida consumiendo SAM. Su inhibición aumenta el pool de nicotinamida disponible para resíntesis de NAD+ y desplaza el metabolismo del adipocito hacia mayor gasto.",
  "research":[
    "Reducción de masa grasa y de tamaño de adipocito sin cambio en la ingesta (ratón con dieta alta en grasa).",
    "Promoción de diferenciación de mioblastos y de regeneración muscular in vitro.",
    "NO existen ensayos clínicos publicados en humano. Toda la evidencia es preclínica.",
    "La inhibición de NNMT tiene implicaciones oncológicas ambivalentes: NNMT está sobreexpresada en varios tumores, pero también participa en homeostasis normal."],
  "halflife":"No caracterizada en humano.",
  "recon":"Soluble en agua y en DMSO. Como molécula pequeña, no requiere las precauciones de un péptido.",
  "storage":"Polvo: −20 °C protegido de la luz. Solución: preparar fresca o alicuotar a −20 °C.",
  "stability":"Buena como sólido. El anillo quinolinio es fotosensible.",
  "handling":"Molécula pequeña de toxicidad no caracterizada. Manejar con guantes; evitar inhalación del polvo.",
  "flags":["Sin aprobación regulatoria. Sin datos en humano.",
           "No es un péptido: los métodos analíticos de la línea (HPLC de péptidos, LC-MS de masa intacta) requieren adaptación."] },

{ "id":"AR", "name":"AICAR", "aka":"Acadesina, AICA ribonucleótido, 5-aminoimidazol-4-carboxamida ribósido",
  "cls":"Molécula pequeña — activador de AMPK (no es un péptido)",
  "cas":"2627-69-2", "formula":"C9H14N4O5", "mw":258.23, "len":None,
  "seq":"No aplica. Es un nucleósido.",
  "purpose":"Investigación del metabolismo energético y de la biogénesis mitocondrial vía AMPK.",
  "contains":"Nucleósido sintético en polvo. Las presentaciones son de masa alta (50–100 MG) porque su potencia molar es baja comparada con los péptidos del catálogo.",
  "mechanism":"Se fosforila intracelularmente a ZMP, que mimetiza el AMP y activa alostéricamente la AMP-quinasa. La AMPK activada aumenta captación de glucosa, oxidación de ácidos grasos y biogénesis mitocondrial, y frena las vías anabólicas.",
  "research":[
    "El famoso «ejercicio en una píldora»: aumento de resistencia de ~44 % en ratón sedentario (Narkar et al., Cell 2008).",
    "Ensayos clínicos humanos en cardioprotección durante cirugía de bypass: resultados mixtos, sin aprobación.",
    "Investigado en leucemia linfocítica crónica por su efecto proapoptótico.",
    "La traducción de los resultados de roedor a humano ha sido pobre; las dosis efectivas en ratón son muy altas en términos de masa."],
  "halflife":"Corta; se elimina rápido y requiere exposición sostenida para efecto.",
  "recon":"Soluble en agua. No requiere precauciones de péptido.",
  "storage":"Polvo: −20 °C. Solución: 2–8 °C corto plazo.",
  "stability":"Buena como sólido.",
  "handling":"Manejar con guantes; evitar inhalación del polvo.",
  "flags":["Sin aprobación regulatoria.",
           "Prohibido por la AMA/WADA (S4.4, moduladores metabólicos) — es uno de los compuestos que motivó la creación de esa categoría.",
           "No es un péptido."] },

{ "id":"MS", "name":"MOTS-c", "aka":"Mitochondrial ORF of the 12S rRNA type-c",
  "cls":"Péptido derivado de mitocondria (MDP)",
  "cas":"1627580-64-6", "formula":"C101H152N28O22S2", "mw":2174.6, "len":16,
  "seq":"MRWQEMGYIFYPRKLR",
  "purpose":"Investigación de homeostasis metabólica y de envejecimiento. Es un péptido codificado por el genoma mitocondrial, no por el nuclear — una clase entera descubierta hace poco más de una década.",
  "contains":"Hexadecapéptido sintético liofilizado, sal de acetato.",
  "mechanism":"Se transloca al núcleo bajo estrés metabólico y regula genes de respuesta adaptativa vía ATF1. Activa AMPK y modula la vía de folato-metionina. Es señalización retrógrada de la mitocondria al núcleo.",
  "research":[
    "Prevención de obesidad inducida por dieta y de resistencia a insulina (ratón).",
    "Mejora de capacidad de ejercicio en ratón envejecido.",
    "Los niveles circulantes en humano descienden con la edad y correlacionan con sensibilidad a insulina (estudios observacionales).",
    "Un polimorfismo de MOTS-c (K14Q) se asocia a longevidad en población japonesa.",
    "Sin ensayos clínicos de intervención publicados."],
  "halflife":"Corta en plasma; el efecto documentado es transcripcional y persiste más.",
  "recon":"Agua bacteriostática. Soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Contiene dos metioninas (posiciones 1 y 6): es el péptido más oxidable de la línea. La oxidación a metionina-sulfóxido añade +16 Da por residuo y se ve en LC-MS. Proteger de aire y de metales traza.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria. Sin datos de intervención en humano.",
           "Prohibido por la AMA/WADA (S4.4)."] },

{ "id":"2S", "name":"SS-31", "aka":"Elamipretida, MTP-131, Bendavia",
  "cls":"Tetrapéptido dirigido a mitocondria",
  "cas":"736992-21-5", "formula":"C32H49N9O5", "mw":639.8, "len":4,
  "seq":"D-Arg-Dmt-Lys-Phe-NH2 (Dmt = 2,6-dimetiltirosina)",
  "purpose":"Investigación de disfunción mitocondrial. Es el compuesto de esta categoría con desarrollo clínico humano más avanzado.",
  "contains":"Tetrapéptido sintético con dos residuos no naturales, liofilizado, sal de acetato. Carga positiva neta, lo que gobierna su comportamiento.",
  "mechanism":"Su alternancia de residuos aromáticos y catiónicos le permite atravesar membranas y concentrarse en la membrana mitocondrial interna, donde se asocia a cardiolipina. Al hacerlo estabiliza la cristae, mejora el acoplamiento de la cadena respiratoria y reduce la producción de especies reactivas de oxígeno. No es un antioxidante que consuma radicales: reduce la fuga que los genera.",
  "research":[
    "Mejora de función mitocondrial en músculo esquelético humano envejecido (fase 1/2).",
    "Ensayos fase 3 en miopatía mitocondrial primaria (MMPOWER-3): objetivo primario no alcanzado.",
    "Aprobación FDA en 2025 para síndrome de Barth bajo la vía acelerada, tras un recorrido regulatorio inusualmente accidentado.",
    "Explorada en isquemia-reperfusión cardíaca y en enfermedad renal (fase 2)."],
  "halflife":"~2–4 h.",
  "recon":"Agua bacteriostática. Muy soluble por la carga catiónica.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Buena. Sin cisteína ni metionina; la Dmt es más resistente a oxidación que la tirosina normal.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Existe versión aprobada por FDA (síndrome de Barth); el material de investigación NO es ese producto."] },

{ "id":"LC", "name":"L-Carnitine", "aka":"Levocarnitina, ácido 3-hidroxi-4-trimetilamoniobutanoico",
  "cls":"Aminoácido cuaternario (no es un péptido)",
  "cas":"541-15-1", "formula":"C7H15NO3", "mw":161.20, "len":None,
  "seq":"No aplica.",
  "purpose":"Transporte de ácidos grasos de cadena larga a la matriz mitocondrial. Es un nutriente esencial condicional, no un compuesto experimental.",
  "contains":"L-carnitina en polvo o solución. Las presentaciones de 600 y 1200 MG reflejan que la dosis fisiológica es de gramos, no de microgramos.",
  "mechanism":"Sustrato obligado del sistema carnitina-palmitoiltransferasa (CPT-1/CPT-2): sin carnitina, los ácidos grasos de cadena larga no cruzan la membrana mitocondrial interna y no se oxidan.",
  "research":[
    "Levocarnitina inyectable está aprobada por la FDA para deficiencia primaria y secundaria de carnitina.",
    "En sujetos con carnitina normal, la suplementación no aumenta de forma consistente la oxidación de grasa (metaanálisis).",
    "La forma D es tóxica y desplaza competitivamente a la L: la estereoquímica del material es un criterio de calidad crítico, no un detalle.",
    "La carnitina oral se convierte parcialmente en TMAO por microbiota intestinal, con asociación epidemiológica a riesgo cardiovascular."],
  "halflife":"Variable; depende de reservas tisulares y de función renal.",
  "recon":"Muy soluble e higroscópica. La forma inyectable se presenta habitualmente ya en solución.",
  "storage":"Polvo: seco y sellado. Muy higroscópico — la ganancia de peso por humedad es la causa más común de error de dosificación.",
  "stability":"Excelente como sólido seco.",
  "handling":"Riesgo bajo. Manejar con buenas prácticas de laboratorio.",
  "flags":["Existe versión aprobada por FDA (levocarnitina); el material de investigación NO es ese producto.",
           "Verificar en el CoA la pureza enantiomérica: la D-carnitina es tóxica.",
           "No es un péptido."] },

{ "id":"MIC", "name":"Lipo-C + B12", "aka":"MIC-B12, inyección lipotrópica",
  "cls":"Mezcla en solución de compuestos lipotrópicos y vitamina B12",
  "cas":None, "formula":None, "mw":None, "len":None,
  "seq":"No aplica. Mezcla, no molécula única.",
  "purpose":"Formulación compuesta clásica de farmacia magistral. Es el único artículo del catálogo que se surte en solución (10 ML) y no liofilizado.",
  "contains":"Composición variable por lote — típicamente metionina, inositol, colina (los tres «MIC») y cianocobalamina o metilcobalamina, en vehículo acuoso con conservador (habitualmente alcohol bencílico). La fórmula exacta de cada lote debe leerse en la etiqueta: no hay una definición estándar de «Lipo-C».",
  "mechanism":"Metionina es donante de metilo y precursor de S-adenosilmetionina; colina e inositol participan en el transporte de lípidos y en la síntesis de fosfolípidos; B12 es cofactor de la metionina sintasa. La lógica es sostener las vías de exportación hepática de lípidos.",
  "research":[
    "No existen ensayos clínicos controlados que demuestren pérdida de peso atribuible a inyecciones lipotrópicas.",
    "La deficiencia de B12 y la de colina son entidades reales con corrección documentada; eso es distinto de la mezcla como agente adelgazante.",
    "El uso es de práctica magistral, no de evidencia."],
  "halflife":"Variable por componente.",
  "recon":"No requiere. Se surte en solución lista.",
  "storage":"2–8 °C, protegido de la luz — la cobalamina es marcadamente fotosensible y el color rosa del vial es su indicador visual.",
  "stability":"Limitada por la cobalamina. Una decoloración del rosa característico indica degradación.",
  "handling":"Contiene conservador. Verificar composición del lote antes de usar.",
  "flags":["Formulación magistral sin estandarización: la composición varía entre lotes y fabricantes.",
           "Sin evidencia clínica de eficacia para pérdida de peso.",
           "Al ser solución y no liofilizado, su vida útil es sustancialmente más corta que la del resto del catálogo."] },

{ "id":"AX", "name":"Adamax", "aka":"Análogo de Semax adamantilado",
  "cls":"Péptido nootrópico — análogo de melanocortina/Semax",
  "cas":None, "formula":None, "mw":None, "len":9,
  "seq":"Declarado por proveedores como Ac-MEHFPGPAG-NH2 con modificación adamantilo. Las descripciones comerciales NO son consistentes entre sí.",
  "purpose":"Investigación de neuroprotección y de BDNF, como análogo estabilizado de Semax.",
  "contains":"Péptido sintético liofilizado. Ésta es la ficha con menor calidad de información pública del catálogo, y la ficha debe decirlo.",
  "mechanism":"Análogo de la familia Semax/ACTH(4-10). La adamantilación aumenta lipofilia y resistencia a proteasas, con la intención de mejorar penetración de barrera hematoencefálica y duración. El mecanismo propuesto es el mismo de Semax: modulación de BDNF y de la vía melanocortinérgica.",
  "research":[
    "NO existen ensayos clínicos publicados.",
    "NO existe una entrada de registro CAS pública ni caracterización estructural revisada por pares.",
    "Toda la información disponible procede de descripciones de proveedores, que difieren entre sí en secuencia y en masa.",
    "La evidencia de la familia (Semax) no es transferible sin datos propios."],
  "halflife":"No caracterizada.",
  "recon":"Agua bacteriostática.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Contiene metionina: oxidable. Proteger de aire.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Compuesto pobremente caracterizado: sin CAS, sin literatura revisada por pares, sin consenso de estructura entre proveedores.",
           "Exigir al proveedor masa intacta por LC-MS y secuenciación: es el único modo de saber qué contiene el vial.",
           "Sin aprobación regulatoria."] },

{ "id":"RA", "name":"Ara-290", "aka":"Cibinetida, péptido de la hélice B de EPO",
  "cls":"Péptido derivado de eritropoyetina, no hematopoyético",
  "cas":"1208243-50-8", "formula":"C51H84N16O21", "mw":1257.3, "len":11,
  "seq":"pyroGlu-EQLERALNSS (pyroglutamato N-terminal)",
  "purpose":"Investigación de neuropatía de fibra pequeña e inflamación tisular. Diseñado explícitamente para separar la protección tisular de la EPO de su efecto sobre glóbulos rojos.",
  "contains":"Undecapéptido sintético con pyroglutamato en N, liofilizado, sal de acetato.",
  "mechanism":"Agonista del «receptor de reparación innata», un heterodímero del receptor de EPO con el receptor beta común (CD131). Ese receptor sólo se expresa en tejido lesionado o inflamado, lo que da selectividad por el sitio de daño. No activa el homodímero EPOR responsable de la eritropoyesis: no aumenta el hematocrito.",
  "research":[
    "Mejora de densidad de fibra nerviosa corneal y de síntomas en neuropatía de fibra pequeña asociada a sarcoidosis (fase 2, humano, n=64).",
    "Reducción de dolor neuropático en diabetes tipo 2 (fase 2, humano).",
    "Ausencia confirmada de efecto sobre hemoglobina y hematocrito en los ensayos humanos — el objetivo de diseño se cumplió.",
    "Sin fase 3 completada; sin aprobación."],
  "halflife":"~2 min en plasma. El efecto es muy superior a la exposición, lo que indica señalización mantenida tras la unión.",
  "recon":"Agua bacteriostática. Soluble.",
  "storage":"Liofilizado: −20 °C. Reconstituido: 2–8 °C, 20–30 días.",
  "stability":"Buena. Sin cisteína ni metionina. El pyroglutamato N-terminal ya está ciclado, lo que bloquea la aminopeptidasa.",
  "handling":"Manejar como sustancia de investigación no caracterizada.",
  "flags":["Sin aprobación regulatoria. Designación de medicamento huérfano en EE. UU. y UE para sarcoidosis.",
           "No confundir con EPO: no es hematopoyético y no comparte su perfil de riesgo trombótico."] },
]
